### ISSUE TITLE
[REQUEST] Support for unique index over multiple (2) fields

### ISSUE THREAD

**Issue by fungilation** [aldeed/meteor-collection2#129]
Something equivalent to this query directly to mongo:
```
> db.media.ensureIndex({content: 1, name: 1}, (unique: true});
Sat Oct  4 01:08:41.657 SyntaxError: Unexpected token :
```

(the statement results in the SyntaxError btw, and I can't see why looking at online example and doc at http://docs.mongodb.org/manual/reference/method/db.collection.ensureIndex/)

**Comment by d4nyll** [comment]
>  I think it's difficult to do things over multiple keys in the schema because then you need some way to link them together, like `indexGroup: 1`, which I think would be more confusing than simply doing `collection._ensureIndex()`.

Would this be possible? Instead of `unique: true`, it becomes `unique: 'indexGroupName'`. Then we take all the `indexGroupName` values in the unique fields, group the fields into their groups, and then do a `collection._ensureIndex()` on each group.

So something like this:

    Schemas.Versionable = new SimpleSchema({
	current: {
		type: Boolean,
		label: "Latest revision"
	},
	rev: {
		type: Number,
		label: "Version No.",
		unique: 'uniqueVersion'
	}
    });
    Schemas.Submissions = new SimpleSchema([Schemas.Versionable, {
	....
	_id: {
		type: String,
		unique: 'uniqueVersion'
	},
        submission: {
		type: String,
		unique: 'uniqueEntry'
	},
	....
    }]);

Will mean something like this:

    db.submissions.ensureIndex({_id: 1, rev: 1}, (unique: true}); // uniqueVersion
    db.submissions.ensureIndex({submission: 1}, (unique: true}); // uniqueEntry

This also allows for cases where multiple unique indices are required. The `_id` field in the `Submissions` schema, and the `rev` field in the `Versionable` schema, will become an unique compound index. And the `submission` values must also be unique.

**Comment by fungilation** [comment]
+1 as user

**Comment by dmitrijs-balcers** [comment]
So guys, is it possible to specify compound indexes using collection2 package?

**Comment by fungilation** [comment]
Not yet. I think I wrote a request issue before

**Comment by davidyaha** [comment]
You will need a way to specify the order of fields in the compound index and then you should specify the sort order as well.
Maybe something like :
```javascript
{
   'field': {
      'compoundIndex': 'name_of_index',
      'compoundIndexOrder': 1,
      'compoundIndexSort': 1
   },
   'secondField': {
      'compoundIndex': 'name_of_index',
      'compoundIndexSort': -1
   }
}
```

But you should note that this way you will get an index that will not used in cases where the primary field sort order and the secondary field sort order is not coordinated as specified. eg:
```javascript
find({} , {sort: {field: 1, secondField: -1}) \\ This will use the index
find({} , {sort: {field: -1, secondField: 1}) \\ This will use the index
find({} , {sort: {field: 1, secondField: 1}) \\ This will not use the index
```

Supporting these cases will ultimately make the collection2 API less simple than the regular collection._endureIndex API. Or if you would like to try and create the indexes without giving the user the opportunity to set those settings you will get a collection that has unused indexes which is worse in my opinion.

**Comment by aldeed** [comment]
This is not worth supporting since the ensureIndex way is less confusing and less code than this would be.

**Comment by fungilation** [comment]
If only _ensureIndex would run without error...

https://github.com/aldeed/meteor-collection2/issues/129#issuecomment-58133558

**Comment by aldeed** [comment]
@fungilation Yeah I guess you have some database corruption or something, but the error would be the same if c2 set up the index since it uses _ensureIndex behind the scenes. I'm guessing you will get the same error in mongo shell, too, so not related to Meteor at all.
