### ISSUE TITLE
How to delete field from DB with autoValue?

### ISSUE THREAD

**Issue by comerc** [aldeed/meteor-collection2#156]
I found this solusion:
```coffee
  "field2":
    optional: true
    type: Number
    autoValue: ->
      if (@value and !@field("field1").value)
        return { $unset: null }
```
It is true-way?

**Comment by aldeed** [comment]
Yes, but you should only return `{$unset: null}` if `@operator` is not `null`. If it's null, then you're not validating a modifier, so returning `{$unset: null}` would be weird.

**Comment by comerc** [comment]
Thank you!

**Comment by jonlachlan** [comment]
This is the behavior I would have expected from ```this.unset()```. I'm glad I found this solution. Perhaps adding this to the docs?

**Comment by aldeed** [comment]
I think it's described pretty clearly in the [autoValue section](https://github.com/aldeed/meteor-simple-schema#autovalue). Feel free to do a pull request with updates to that section if necessary.

**Comment by jonlachlan** [comment]
I may be having an issue here. I have been trying to figure out how to use this.unset(), but I can't seem to get it to do anything. 

Suppose I want ```field1``` to be ```unset``` if the user enters the value of 0. (This is just an example, not my actual use case, but it should work all the same.) 
```javascript
field1: {
 type:Number,
 optional:true,
 autoValue: function () {
  if (this.value === 0) {
    return {$unset:null}
  }
 }
```
When I try to set field1 to 0, this should make the value go away altogether (including if there was a previous value). However, nothing happens. On the other hand, if I make field1's value dependent on an update to field2, the pattern works:

```javascript
field1: {
 type:Number,
 optional:true,
 autoValue: function () {
  var field2 = this.field("field2");
  if (field2.value === 0) {
    return {$unset:null}
  }
 }
```
When I set field2 to 0, any previous value for field1 is removed.

Based on the documentation, it seems like this is what ```this.unset()``` is supposed to do. When I try to use it, however, it seems that the update just doesn't complete -- it doesn't unset the existing value if there was one.

I hope this makes sense. Perhaps it should be made into another thread? 

Thanks so much for the packages you've published, they are truly invaluable (not to mention super cool).

**Comment by aldeed** [comment]
Yes, @jonlachlan, can you submit a new issue so we can track it?
