### ISSUE TITLE
uniqueness within the array (a set)

### ISSUE THREAD

**Issue by MaazAli** [aldeed/meteor-collection2#159]
I have a field in my schema that is an array, I want this array to act more like a set (only have unique objects). How can I enforce this through collection-2? Is there some sort of uniqueness check per array? 

For example: 
..
..
.. 
```
	entries: {
		type: [Object],
		optional: true
	},
	"entries.$.contentId": {
		type: String

		uniqueWithinArray: true // something like this? 
	},
	"entries.$.sortOrder": {
		type: Number,
		min: 1,
		max: 100, // This max should match with the entries maxCount
	},
	"entries.$.comment": {
		type: String,
		min: 1,
		max: 500,
		optional: true
	},
```

So in this example, ensure that all objects in this array have a unique contentId? 

or to just have a property for entries called `arrayIsSet: true` which will ensure that each object within the array is unique, however, it could be a little annoying to figure out if one object is equal to another and I suppose in this context it would be when both of them have the same fields with the same values.

**Comment by aldeed** [comment]
Collection2 relies on mongo for uniqueness validation, and mongo doesn't currently support unique indexes within arrays in the same doc. So a check for uniqueness will require a database lookup. It's possible that this could be coded into collection2 for convenience, but you can also do it now with a custom function, where you do the `findOne` call in your function and return `"notUnique"` string if a doc is found.

**Comment by MaazAli** [comment]
I'm thinking of something much simpler. Nothing to do with mongodb. Just check that elements within an array are unique.

For example if we have array of numbers and we want that array to be unique. so we can't have [2,2,4,4], the check would fail. So essentially have validation for arrays to act as sets.

**Comment by aldeed** [comment]
But without a database lookup, there's no way to ensure that it stays unique when doing an update.

**Comment by aldeed** [comment]
Even though schemas can be used for non-database purposes, it confuses people if there's an option that doesn't actually do what it says in a database situation.

**Comment by aldeed** [comment]
Closing this. If we want a `uniqueItems` option for non-database purposes, that would be something in simple schema pkg.
