### ISSUE TITLE
[Question] Validate unit conversion with transform

### ISSUE THREAD

**Issue by mattkrick** [aldeed/meteor-collection2#160]
I'm trying to work with users who use metric & standard.
In my collection, I have a 'distance' field with a max value of 10,000 meters.
My collection's transform function converts the units to miles or kilometers, depending on the user's preference (let's say miles).
I have an autoform field that asks for the distance in miles.
How can I validate that the user-input value is less than the schema max? ie make it invalid if the input is over ~6.2 miles, which is 10,000 meters. Am I on the right course or am I way off?

**Comment by aldeed** [comment]
Maybe add an `autoValue` that does `return this.value * conversionFactor`, where you determine `conversionFactor` by doing a `findOne` database lookup for wherever their preference is stored? Otherwise if it's just one autoform, you can handle the conversion in a `before` hook.

**Comment by mattkrick** [comment]
Woah! What a clever way to use autoValue, works like a charm!
