### ISSUE TITLE
security

### ISSUE THREAD

**Issue by h4818** [aldeed/meteor-collection2#162]
This is not an issue, but rather a question.
Should the schema (simple/collection2) be defined in a common file? Is it not a security concern to have the schema available to all users? 

What about defining the collection in the "lib" directory and the attaching the schema in the "server" directory

**Comment by aldeed** [comment]
If the data is extra sensitive, you can attach on server only. It should work fine with client only, server only, or both. You will have unnecessary trips to server, though, so in most cases it's best to define in common code. As long as you apply proper security, there is nothing to worry about.

Remember that Meteor mirrors data on the client anyway, so one can also see the "schema" by simply looking at the document on the client (unless of course there are properties you're not publishing).
