### ISSUE TITLE
Getting 'Upsert not allowed in a restricted collection' when attaching schema to collection

### ISSUE THREAD

**Issue by waiholiu** [aldeed/meteor-collection2#165]
Hi,

Sorry I'm learning how to use your library. I'm coming across some behaviour that I'm finding strange.

I'm using the Upsert command to insert or update a documnent in a collection. However, when I attach it to a collection2 schema, it seems to be giving me the error 

update failed: Access denied. Upserts not allowed in a restricted collection.

I created a sample solution here
https://github.com/waiholiu/collection2Upsert/tree/master

the Master branch I have a collection that's attached to a schema. If you run the solution, you'll see that it returns this error.

However, I also created a withoutCollection2 branch where I've commented out the line where I attach the schema and the error no longer appears.

I'm aware that I can just insert or update the document, but I'm just curious why Upsert does not seem to work here.

**Comment by waiholiu** [comment]
Hi, I think the problem is that in Meteor, upsert's automatically get denied on the client side whenever there are Allow rules defined. 

See https://github.com/meteor/meteor/issues/1587

According to the meteor team, this is intentional.

Your collection2 library must be defining allow rules which is why when I attach the schema, it displays that message.

**Comment by aldeed** [comment]
Yes, collection2 works by defining `deny` rules. Meteor does not currently allow upserts from untrusted code (and it would be difficult if not impossible to do so).

**Comment by llvasconcellos** [comment]
So GOD DAMN document it!!!
