### ISSUE TITLE
Unique with Mongodb 2.6.7

### ISSUE THREAD

**Issue by katywings** [aldeed/meteor-collection2#166]
FYI: I've read about many problems with the unique field. Now i found one more :D :dancer: 

It seems, the unique field doesnt work with the current version of mongodb (2.6.7)
Example: If you define unique at the username field it will detain the server from starting up.

(I know, meteor doesnt officially support 2.6 :yum: )

**Comment by aldeed** [comment]
OK. I wasn't planning to worry about current mongo version until Meteor supports it.

**Comment by glasser** [comment]
I'm not sure what you're talking about here.  Unique indexes?  They should work.

I appreciate that you're trying to help by filing this issue, but can you follow our [guidelines on reporting a bug](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor) including demonstrating a reproduction?

**Comment by aldeed** [comment]
Since Meteor will support 2.6 in the next release, we should probably look into this. See also #179

**Comment by fabienb4** [comment]
Here it is in the 2.6 [compatibility page](http://docs.mongodb.org/manual/release-notes/2.6-compatibility/#ensureindex-and-existing-indexes).

> db.collection.ensureIndex() now errors:

> if you try to create an existing index but with different options; e.g. in the following example, the second db.collection.ensureIndex() will error.

> `db.mycollection.ensureIndex( { x: 1 } )`
> `db.mycollection.ensureIndex( { x: 1 }, { unique: 1 } )`

> if you specify an index name that already exists but the key specifications differ; e.g. in the following example, the second db.collection.ensureIndex() will error.

> `db.mycollection.ensureIndex( { a: 1 }, { name: "myIdx" } )`
> `db.mycollection.ensureIndex( { z: 1 }, { name: "myIdx" } )`

> Previous versions did not create the index but did not error.

I'm not sure that there is anything to fix in collection2...?

We just have to make sure not to try to override an index previously set. Which would probably occur only when using packages anyway, and well, package author should index the proper fields, right? ;-)

**Comment by jykae** [comment]
@katywings @aldeed Is this still issue or can we use ensureIndex and trust that it works as supposed to?

**Comment by aldeed** [comment]
Closing old issues. Please comment if this is still an issue and should be reopened.
