### ISSUE TITLE
simple-schema version is outdated

### ISSUE THREAD

**Issue by ernestorocha** [aldeed/meteor-collection2#167]
Why the version used by this package is ```aldeed:simple-schema@1.0.3``` and not the ```1.3.0``` ? Is this a typo or should I ```add  aldeed:simple-schema``` separately ?

**Comment by aldeed** [comment]
It shouldn't matter. Meteor will use the latest release it can within the same major version.

**Comment by ernestorocha** [comment]
It's not working here, I'm still facing this bug on ```simple-schema``` https://github.com/aldeed/meteor-simple-schema/issues/168 and all I have is the ```collection2``` package.

```
meteor update
This project is already at Meteor 1.0.3.1, the latest release.
Your packages are at their latest compatible versions.
```

**Comment by aldeed** [comment]
OK, maybe you need to explicitly add it to your project then. There used to be an issue with updating implied dependencies, but I thought they had fixed that.

We can update the C2 dependency, too.
