### ISSUE TITLE
Trouble using this.unset()

### ISSUE THREAD

**Issue by jonlachlan** [aldeed/meteor-collection2#168]
I have been trying to figure out how to use ```this.unset()```, but I can't seem to get it to do anything.

Suppose I want ```field1``` to be unset if the user enters the value of 0. (This is just an example, not my actual use case, but it should work all the same.)
```javascript
field1: {
 type:Number,
 optional:true,
 autoValue: function () {
  if (this.value === 0) {
    return {$unset:null}
  }
 }
```

When I try to set field1 to 0, this should make the value go away altogether (including if there was a previous value). However, nothing happens. On the other hand, if I make field1's value dependent on an update to ```field2```, the pattern works:
```javascript
field1: {
 type:Number,
 optional:true,
 autoValue: function () {
  var field2 = this.field("field2");
  if (field2.value === 0) {
    return {$unset:null}
  }
 }
```
When I set field2 to 0, any previous value for field1 is removed.

Based on the documentation, it seems like this is what ```this.unset()``` is supposed to do. When I try to use it, however, it seems that the update just doesn't complete -- it doesn't unset the existing value if there was one.

I hope this makes sense. 

Thanks so much for the packages you've published, they are truly invaluable (not to mention super cool).

**Comment by aldeed** [comment]
`this.unset()` has nothing to do with existing data. It will simply delete any part of the document or modifier that would affect that field, if the insert or update succeeds.

But I do agree that `return {$unset:null}` should work. Can you provide a reproduction repo or MeteorPad that shows the issue?

**Comment by jonlachlan** [comment]
Yes I'll do this tomorrow.
