### ISSUE TITLE
Complex object examples

### ISSUE THREAD

**Issue by victorbstan** [aldeed/meteor-collection2#170]
Hello, this is more of a question than bug report, I hope it's OK... I have a more complex (relatively) object to validation, specifically, what is the bet way to write a schema for something like the following?

```
{
  name: String
  profile: {
    nickname: String,
    education: [
      {
        schoolName: String,
        graduated: Date
      }
    ]
   ...
  }
}
```

In the above, how would I validate `education` that it's an optional array, that when present contains the required set of keys? Or that `profile` is an object? 

Is it customary to break down each sub-object and have a schema definition for it? Or is there a way to do it 'inline'? 

On a related note:

Meteor `check` has options like: `Match.Optional()`, `Match.OneOf()`, etc... and it's possible to then pass in object or arrays with the sub-structure or types to be checked against in these methods...

**Comment by aldeed** [comment]
SimpleSchema doesn't use the `check` pkg. Schemas are flat and you use mongo's notation to define everything.

```js
{
  name: { type: String },
  profile: { type: Object },
  'profile.nickname': { type: String },
  'profile.education': { type: Array, optional: true },
  'profile.education.$': { type: Object }
  'profile.education.$.schoolName': { type: String }
  'profile.education.$.graduated': { type: Date }
}
```

If you want a separate `EducationSchema` schema that has `schoolName` and `graduated` defined within it, then you would instead do:

```js
{
  name: { type: String },
  profile: { type: Object },
  'profile.nickname': { type: String },
  'profile.education': { type: Array, optional: true },
  'profile.education.$': { type: EducationSchema }
}
```

Either way is fine, but having granular schemas can come in handy if using in multiple collections or as autoform schemas.

**Comment by victorbstan** [comment]
OK, those are some good examples :) thanks! Would be nice to show them in the docs as well! Just a thought.
