### ISSUE TITLE
How to validate an array with mixed types

### ISSUE THREAD

**Issue by yanndebelgique** [aldeed/meteor-collection2#172]
I've got an array that looks like the following : 
var arr = ["foo", 1,3, ...]
I want to verify that the first element of arr is a string and that the other values are integers.
Is this possible?
If not possible it would be really cool to add a custom validation function on the schema for a specific field so we can cover more complex cases.

Thanks

**Comment by yanndebelgique** [comment]
ok found what I was looking for!

**Comment by yanndebelgique** [comment]
Ok not quite :(

I found that you can add custom function but you still need to define a type. So its seems that if the type is not the same it invalidates it. So it doesn't seem straightforward to do the validation I want to do.

**Comment by aldeed** [comment]
There are plans eventually for the simple-schema pkg to support multiple types.
