### ISSUE TITLE
autoValue should not run for insert/update when denyInsert/denyUpdate is true

### ISSUE THREAD

**Issue by boustanihani** [aldeed/meteor-collection2#173]
How about implementing `createdAt` with the following code:

``` javascript
createdAt: {
    type: Date,
    denyUpdate: true,
    autotValue: function() {
        return new Date(); // forceValue
    },
},
```

Instead of using this code (https://github.com/aldeed/meteor-collection2#autovalue):

``` javascript
createdAt: {
    type: Date,
    autoValue: function() {
        if (this.isInsert) {
            return new Date;
        } else if (this.isUpsert) {
            return {
                $setOnInsert: new Date
            };
        } else {
            this.unset();
        }
    },
},
```

**Comment by aldeed** [comment]
They will have two different effects. `denyUpdate` will result in a validation error when you try to update that field, and your update will fail. The longer autoValue will simply alter the modifier to remove any attempts to update that field, and then the rest of the update will potentially succeed. So it depends on whether you want errors or just a silent guard against mistakes.

**Comment by boustanihani** [comment]
My code also hast one issue, ```autotValue``` will always try to generate a new value for ```createdAt``` during any update operation for the parent object and of course this operation will then fail. **Don't you think that autoValue should not autorun again during an update operation when combined with denyUpdate?**

**Comment by aldeed** [comment]
You're probably right except that `autoValue` is a simple-schema thing and `denyUpdate` is a collection2 thing, so it may be very difficult to fix that. I'll leave this open and investigate eventually.

**Comment by boustanihani** [comment]
I once had this idea I'd like to share, do you think merging SimpleSchema, Collection2 & AutoForm would be a good idea :) ?

**Comment by aldeed** [comment]
No. :) There is no need to add code to your project that you're not using, and a lot of people use SS alone, or use SS+C2 without autoforms.

**Comment by boustanihani** [comment]
I agree :+1:

**Comment by davidworkman9** [comment]
+1
