### ISSUE TITLE
Error Order

### ISSUE THREAD

**Issue by rishiag** [aldeed/meteor-collection2#176]
I am using collection2 independently i.e. without autoform. In case of invalidation during insert Is there any particular order of keys in which collection2 returns the error? I tried to find the pattern but it's not alphabetically, not according to order defined in object sent or declared in Schema. There is a particular order but I am not able to find what it is.

**Comment by aldeed** [comment]
I'm not sure I know the exact answer. In the SS package, there is a `MongoObject` beast that recurses through the object and essentially flattens it. It hides the differences between an insert document and an update modifier. Then I think validation sort of loops through that flattened doc, but with some side trips. I'm going from memory so I could be wrong.

I'm also pretty sure it returns only the first error per key.

Does it matter?

**Comment by rishiag** [comment]
Hey Eric,
Thanks for the reply. The issue is that when user submits the form, I want to show him the errors in the order of fields in the form. For eg. if fields A & B fails validation and A is above B, I want to show him error first for A because its position is above field B in the form but collection2 returns the error for field B. Getting only one error is not a problem as I am showing errors in the notification form.

**Comment by aldeed** [comment]
Collection2 is unaware of the order of form fields so you would have to manually order them.
