### ISSUE TITLE
Is there a way to not let a value to be updated once is set at the first time?

### ISSUE THREAD

**Issue by diegoalberto** [aldeed/meteor-collection2#178]
I have an unique indexed value called id, that must be an incremental integer, there are holes that could not be used, but the system is enabling me to modify them.  I can ensure that this does not happens not enabling users to update that field value. How to do that? Thanks =D

**Comment by aldeed** [comment]
Did you try `denyUpdate: true` in the schema for that key?

**Comment by diegoalberto** [comment]
Thanks, it did work.
