### ISSUE TITLE
update() callback returns object when it should return 'number of affected documents'

### ISSUE THREAD

**Issue by ianjonesidau** [aldeed/meteor-collection2#181]
Collection.update() callbacks with Collection2 return an object (with affected fields) rather than the expected 'number of affected documents'.

Collection2 also seems to be mutating passed in data rather than making a defensive clone, see: http://stackoverflow.com/questions/28581994/collection-callback-ignoring-scope-variable/

**Comment by aldeed** [comment]
I made sure c2 returns and passes everything the same as normal collections, and I think we have tests for it. If you're seeing different behavior, you'll need to provide a reproduction in a repo or MeteorPad.

SimpleSchema does mutate the object on cleaning it. This is required for things to work properly on the server side of client-initiated operations. However, maybe we can clone in the other two cases where validation happens, which are the only two that anyone would notice anyway.

**Comment by ianjonesidau** [comment]
I think you're right, I also have SimpleSchema running. It's mutating the update return, which is unexpected. Thanks for looking at this.
