### ISSUE TITLE
Unable to use floating point numbers for Number type.

### ISSUE THREAD

**Issue by jleach** [aldeed/meteor-collection2#185]
I have a Number data type in the schema but am unable to store floating point numbers in it:

```
Schema.Coordinates = new SimpleSchema({
    lng: {
    	type: Number,
    	min: -180.0,
    	max: 180.0
    },
    lat: {
    	type: Number,
    	min: -90.0,
    	max: 90.0
    }
});
```

When I try to insert anything other than an integer (anything with xxxx.0) I get a validation error:
```
W20150222-20:24:23.523(-8)? (STDERR) Error: Lng must be an integer
```

**Comment by kylestew** [comment]
I'm having the same issue, what is the solution?

**Comment by kylestew** [comment]
Sorry, found the solution. This is actually part of SimpleSchema.
https://github.com/aldeed/meteor-simple-schema/blob/7bfc45656cf129eb48a397a244628cc01032b9b7/README.md#decimal

**Comment by jedwards1211** [comment]
@aldeed why is this the default behavior?  Everyone is used to `Number` meaning floating point in JS.

**Comment by aldeed** [comment]
@jedwards1211 I actually agree, but I did it like this for some reason initially and I figured it would be pretty confusing and a lot of work to change it on everyone. Someday I might.

**Comment by jedwards1211** [comment]
@aldeed I see, yeah that's always a tough situation.  If you decide to you could try having a deprecation with ample console warnings phase like React is currently doing for their transition from 0.13 to 0.14.  I'm glad you agree though :)

**Comment by jedwards1211** [comment]
Or if it started as an opt-in config switch, I would be happy to use that switch

**Comment by aldeed** [comment]
See https://github.com/aldeed/meteor-simple-schema/issues/466
