### ISSUE TITLE
How to turn off SimpleSchema.clean for third-party packages

### ISSUE THREAD

**Issue by xumx** [aldeed/meteor-collection2#186]
SimpleSchema automatically filters out value for Collections with no schema attached. Conflicting with many third-party packages where I couldn't include { filter: false }  to their mongo insert/update calls.

Some packages I have trouble with are velocity and meteorhacks:cluster

**Comment by aldeed** [comment]
Just skimmed through the code and I'm pretty sure it doesn't do anything if you haven't called `attachSchema` at least once on the collection, so maybe there's something else going on here. Maybe you can create a reproduction.

We should add tests for this to be doubly sure it's not, though.
