### ISSUE TITLE
Docs don't give any examples on how to pass options to insert/update

### ISSUE THREAD

**Issue by ShimShamSam** [aldeed/meteor-collection2#187]
The docs say to set the *filter* option to false when inserting or updating, but I don't know what that means. There are no examples. Does Collection2 change the signature of insert/update?

**Comment by aldeed** [comment]
Yes, we should update the docs. `update` already takes options, but collection2 changes the `insert` signature to also accept options in the same way. You can see an example of passing options [here](https://github.com/aldeed/meteor-collection2#validation-contexts).
