### ISSUE TITLE
updatedAt autoValue is firing twice on my observeChanges changed callback

### ISSUE THREAD

**Issue by mattkrick** [aldeed/meteor-collection2#190]
My `updatedAt` field in my schema looks just like what's in the doc:
```
  updatedAt: {
    type: Date,
    autoValue: function() {
      if (this.isUpdate) {
        return new Date();
      }
    },
    denyInsert: true,
    optional: true
  },
```

My `changed` callback on my `observeChanges` method and `update` in my `Meteor.method` are both very simple:
```
      changed: function (id, fields) {
        console.log(id, fields);
      }

  toggleStopId: function (stopId, personId) {
    People.update(personId, {'$set': {myStop: stopId}});
  }
```

The result is 2 calls to the `changed` callback:
```
BfEb6F7ndGeDdmbEK Object {myStop: "9AZb2LgDGAQxPjNHg", updatedAt: Wed Mar 11 2015 17:42:01 GMT-0600 (CST)}
BfEb6F7ndGeDdmbEK Object {updatedAt: Wed Mar 11 2015 17:42:01 GMT-0600 (CST)}
```

Could you please tell me what I'm doing wrong to cause the 2nd call?

**Comment by aldeed** [comment]
I can't think of anything. If you can post full reproduction code, it would be helpful to step through.

**Comment by mattkrick** [comment]
I found another bug I *think* has the same root cause, so here it is reproduced:
http://meteorpad.com/pad/Yo9df9KgT9Mh7hyWd/Leaderboard
When you click on the erlenmeyer flask logo in the meteor pad, it triggers an upsert which has the `createdAt` field auto-generated.
The error is `MongoError: Cannot update 'createdAt' and 'createdAt' at the same time`
P.S. I think this error was `MongoError: Field name duplication not allowed with modifiers` in Mongo 2.4

I `console.log(this)` on the `autoValue` & as the console shows, `autoValue` is hit twice: once with `value: undefined` and another with a correct `new Date` value.

I don't know where in your code to look, but I think an unnecessary `changed()` trigger might occurring? It seems erroneous that `autoValue` is triggered twice.

**Comment by apacala** [comment]
Same error here.

**Comment by ThomasCin** [comment]
Still have this problem, as in the Leaderboard example. Upsert results in autoValue being called twice, and the MongoError: `Cannot update 'createdAt' and 'createdAt' at the same time`.

I use the example code from the autoValue documentation:

```
{
  // Force value to be current date (on server) upon insert
  // and prevent updates thereafter.
  createdAt: {
    type: Date,
    autoValue: function() {
      if (this.isInsert) {
        return new Date;
      } else if (this.isUpsert) {
        return {$setOnInsert: new Date};
      } else {
        this.unset();
      }
    }
  },
```

Any ideas?
