### ISSUE TITLE
Problem with Meteor 1.0.4.1

### ISSUE THREAD

**Issue by juliancwirko** [aldeed/meteor-collection2#192]
Something with indexes...

After update to Meteor 1.0.4.1 I get:

```
MongoError: Index with pattern: { username: 1 } already exists with different options
...
at packages/aldeed:collection2/collection2.js:61:1
```

**Comment by fabienb4** [comment]
See aldeed/meteor-collection2#166

**Comment by juliancwirko** [comment]
So this:
https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_server.js#L1309

and this:
https://github.com/aldeed/meteor-collection2/blob/master/collection2.js#L61

is the problem? How can we fix this?

**Comment by fabienb4** [comment]
Don't set `index: true` or `unique: true` for `username` in `Meteor.users` schema.

Do something like this:
```javascript
  username:  { type: String, regEx: /^[a-z0-9A-Z_]{3,15}$/ },
```

Same applies for any package that already defined an index on a collection.

**Comment by juliancwirko** [comment]
so I understand that this is a collection2 problem? Am I right?

**Comment by aldeed** [comment]
Will track in #166

**Comment by aldeed** [comment]
As far as users schema, there's really no bug here. If you remove `unique` and `index` props from all accounts-managed fields in the user schema, everything should work fine.

The only thing I plan to do is catch and ignore or improve the error message to clarify this.

**Comment by juliancwirko** [comment]
Ohhh, ok, I understand it now, thanks.

**Comment by DKarp** [comment]
> If you remove unique and index props from all accounts-managed fields in the user schema, everything  should work fine.

but in this case we have on server side:

    Exception in callback of async function: MongoError: E11000 duplicate key error index: meteor.users.$username_1  dup key: { : "not_unique_username" }

and on client side: 

    -> Meteor.users.simpleSchema().namedContext().invalidKeys() 
    <- [] //empty array, so no errors
