### ISSUE TITLE
Unique index not works on *.meteor.com hosting

### ISSUE THREAD

**Issue by elbowz** [aldeed/meteor-collection2#195]
I don't know if this is related to https://github.com/aldeed/meteor-collection2/issues/166

btw, the **index** is not create on the remote MongoDB.

**Comment by aldeed** [comment]
If it's on Meteor.users, then it's probably the same. The solution is to remove the `unique` and `index` from your schema definition since it's already defined by the accounts packages.

**Comment by elbowz** [comment]
In really is in a my own defined collection:
```
 name: {
        type: String,
        label: 'Title',
        index: true,
        unique: true
    }
```

on local:
```
meteor:PRIMARY> db.system.indexes.find()
{ "v" : 1, "key" : { "_id" : 1 }, "ns" : "meteor.workflow", "name" : "_id_" }
{ "v" : 1, "name" : "c2_name", "key" : { "name" : 1 }, "unique" : true, "ns" : "meteor.workflow", "background" : true, "sparse" : false }
```

on remote:
```
production-d:PRIMARY> db.system.indexes.find()
{ "v" : 1, "name" : "_id_", "key" : { "_id" : 1 }, "ns" : "*_meteor_com.system.users" }
{ "v" : 1, "name" : "user_1_userSource_1", "key" : { "user" : 1, "userSource" : 1 }, "unique" : true, "ns" : "*_meteor_com.system.users" }
{ "v" : 1, "name" : "_id_", "key" : { "_id" : 1 }, "ns" : "*_meteor_com.workflow" }
```

thanks for your ultra speedy answer :)

**Comment by aldeed** [comment]
Try adding the index yourself in your server code and deploying.

`collection._ensureIndex({ "name" : 1 }, {
        background: true,
        name: 'c2_name',
        unique: true,
        sparse: false
      });`

Remove `index` and `unique` from name schema first.

**Comment by elbowz** [comment]
Works good!

Also the form validation appear:
```<span class="help-block">Title must be unique</span>```

**Comment by aldeed** [comment]
OK, it's really strange that it doesn't work through collection2 then, because that's the same exact call collection2 makes for you when you have `index` and `unique` in the schema.

**Comment by elbowz** [comment]
oohh, shit...I'm a stupid guy! sorry

I did `collection.attachSchema(schema, { replace: true });` on client side (because I have to change *live* the document validation on the same collection).

Instead, on localhost I had already created the unique key...

sorry again...and thanks!
