### ISSUE TITLE
Insert rise TypeError: S is not a function

### ISSUE THREAD

**Issue by achirkof** [aldeed/meteor-collection2#199]
Hello.
I have collection and simple schema
```javascript
var Schemas = {};
SimpleSchema.debug = true;
Weight = new Mongo.Collection("weight");
Schemas.UserWeight = new SimpleSchema({
    createdBy: {
        type: String
    },
    weight: {
        type: String
    },
    createdAt: {
        type: Date
    }
});
Weight.attachSchema(Schemas.UserWeight);
```
and I have an insert
```javascript
 Weight.insert({
                weight: weightVar,
                createdAt: new Date(),
                createdBy: measureOwner
            }, function(error, result){
                console.log(error.invalidKeys);
            });
```
and insert raize an error `TypeError: S is not a function` in file `aldeed_simple-schema.js:2618`.

**Comment by achirkof** [comment]
It is on client side. I see it on browser's console in debug mode. Is it possible to conflict with another plugin?

**Comment by aldeed** [comment]
Are you using pkgs that enable requirejs? That might cause this.

**Comment by achirkof** [comment]
There is list of my packages:
accounts-password       1.1.0  Password support for accounts
accounts-ui             1.1.5  Simple templates to add login widgets to an app
aldeed:collection2      2.3.2  Automatic validation of insert and update operations on the client and server.
autopublish             1.0.3  Publish the entire database to all clients
email                   1.0.6  Send email messages
gadicohen:famous-views  0.1.32  Blaze Views for Famous; doing Famous Meteor-style
insecure                1.0.3  Allow all database writes by default
iron:router             1.0.7  Routing specifically designed for Meteor
jquery                  1.11.3_2  Manipulate the DOM using CSS selectors
meteor-platform         1.2.2  Include a standard set of Meteor packages in your app
mizzao:bootstrap-3      3.3.1_1  HTML, CSS, and JS framework for developing responsive, mobile first projects ...
mrt:moment              2.8.1  Moment.js, a JavaScript date library for dates, packaged for Meteor. See http:/...
raix:famono             0.9.27  Library bundler supports use of libraries like Famous, via git/bower and requi...

**Comment by aldeed** [comment]
Yeah, `raix:famono` is the culprit as that adds requirejs support. It's really an issue with the simple-schema package, though. It should be a little smarter about making sure `window.S` is defined. I created an issue to track here: https://github.com/aldeed/meteor-simple-schema/issues/317
