### ISSUE TITLE
fields with autoValue are automatically added to validation list on updates

### ISSUE THREAD

**Issue by mattkrick** [aldeed/meteor-collection2#203]
I'm doing an update where I set a single field:

`return Col.update({_id: '123'}, {$set: {foo: 'bar'}});`

The write fails with a response of a sanitization error on another unrelated field. (callstack below).
```
I20150401-19:19:51.950(-6)?     at getErrorObject (packages/aldeed:collection2/collection2.js:369:1)
I20150401-19:19:51.950(-6)?     at [object Object].doValidate (packages/aldeed:collection2/collection2.js:352:1)
I20150401-19:19:51.950(-6)?     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed:collection2/collection2.js:154:1)
```
That unrelated field was erroneously added to the list of fields to validate because of its `autoValue`:
```
autoValue: function () {
        return this.value * 1.6;
      }
```

The problem is solved (albeit in a hacky manner) by doing this:
```
autoValue: function () {
        if (!this.value) return;
        return this.value * 1.6;
      }
```

I think this is due to `autoValue` being called more often than necessary & if so, could be the cause of other issues (#190)

**Comment by aldeed** [comment]
This is the purpose of `autoValue`. It's always called for every field, allowing you to enforce defaults, force a value, ensure a prop is never changed, etc. It's very flexible but requires a lot of logic in the function to work correctly.

**Comment by mattkrick** [comment]
That makes sense & I realize selectively running only the dependent autoValues would require a lot of logic for creating Deps. So if none of my autoValue functions involve other fields, the above is the best way to get around this?

**Comment by aldeed** [comment]
It depends on what your goal is. It doesn't seem like nearly enough logic to be correct. For example, if you do an update with `{$inc: {foo: 1}}`, then `this.value` will be 1 and `this.operator` will be "$inc". I doubt you want to multiply the increment. But if you only do updates on the server and you know you will never use any operator except `$set`, then it might be OK. The key is to make sure you think about and handle all possible update operators.
