### ISSUE TITLE
Unique callback not returning error to the client

### ISSUE THREAD

**Issue by florasolutions** [aldeed/meteor-collection2#206]
Hi,

First up: thanks for building some awesome meteor packages!

Now to the point... I have a field which should be unique in a collection. The problem is, when the unique error is returned by MongoDB and I can properly handle the response to the client, the client is already continuing its business without ever receiving the error.

I've looked into this issue: http://stackoverflow.com/questions/21435978/collection2-insert-using-method-exception-from-unique-constraint-not-caught and https://github.com/aldeed/meteor-collection2/issues/59 (both pretty old already) - I could get the workaround to work, but I was wondering if this is still the right way to do it.

I'm using: meteor 1.0.5, separate instance of mongodb 2.6.8, collection2 2.3.3

I have the following in one of my schemas:

```
Customer = new SimpleSchema({
        'code': {
            type: String,
            min: 1,
            max: 20,
            optional : false,
            unique : true,
            label : 'Customer Code',
            regEx : App.RegEx.CustomerCode
        }
});

Customers = new Mongo.Collection('customers');
Customers.attachSchema(Customer);
```

Validation works fine on the client side. Pretty cool stuff. On the client side, I have the following code:

```
var customer = {
    code : '123456'
};

Meteor.call('addCustomer', customer, function (error, result) {
    if (error) {
        alert('Error');
    } else {
        alert('Nice!');
    }
});
```

...and the following method on server side:

```
Meteor.methods({

    addCustomer: function(customer) {
        Customers.insert(customer, function (error, result) {
            if (error) throw new Meteor.Error('insert-error',error);
        });
    }
});
```

Inserting works fine. Great! Now, I want to insert a customer with the same code to test the unique constraint on the field.

What happens is that the client in this case never receives the error and displays the 'Nice!' alert.

On server side, the callback is properly ran, but the throw never "reaches" the client.

Any idea what might be happening?

**Comment by aldeed** [comment]
In your method, do `Customers.insert(customer)` (no callback). Methods have to execute synchronously to work properly, and any errors thrown will be in the `error` argument back on the client. Collection2 attaches a sanitized error with extra information, so that you'll be able to see the validation errors back on the client by examining the `error` object.

**Comment by bjones6** [comment]
I did as you described and I'm getting a bland code 500 error on the client despite the fact that I'm getting an "E11000 duplicate key error index" exception in the server console.

```javascript
// see it's synchronous
Contacts.insert({
    userIds: [Meteor.userId()],
    name: name,
    phone: phone,
    email: email,
    createdAt: date
});
```

```javascript
// and on the client
Meteor.call('newContact', name, phone, email, (err) => {
    if (err){
        console.log(err);
        alert(err.reason);
    } else {
        $scope.popup.close();
    }
});
```

And for what its worth thanks for writing and maintaining this awesome package

**Comment by pdewouters** [comment]
I have the same issue.
