### ISSUE TITLE
inserting array string doesnt work

### ISSUE THREAD

**Issue by adriannatabio** [aldeed/meteor-collection2#210]
Here is my schema:

```js
Schema = {};

Schema.UserProfile = new SimpleSchema({
    fullname: {
        type: String,
        label: 'Full name',
        min: 2,
        max: 100
    },
    gender: {
        type: String,
        allowedValues: ['Male', 'Female'],
        label: 'Gender',
        optional: true
    },
    organization : {
        type: String,
        label: 'Organization',
        min: 3,
        max: 100,
        optional: true
    },
    bio: {
        type: String,
        label: 'Bio',
        optional: true
    }
});

Schema.User = new SimpleSchema({
    username: {
        type: String,
        min: 4,
        max:20,
        label: "Username"
    },
    createdAt: {
        type: Date,
  		autoValue: function() {
    		if (this.isInsert) {
      			return new Date;
    		} else if (this.isUpsert) {
      			return {$setOnInsert: new Date};
    		} else {
      			this.unset();
    	    }
      	}
    },
    profile: {
        type: Schema.UserProfile,
        optional: true
    },
    services:{
        type: Object,
        optional: true,
        blackbox: true    
    },
    allowedAccounts:{
        type: [Object],
        optional: true
    },
    'allowedAccounts.$.accountId': {
        type: String
    },
    'allowedAccounts.$.authorizedBy': {
        type: String,
        autoValue: function(){
            return this.userId;
        }
    },
    
});
```

Here is the sample data I inserted:

```js
{
 allowedAccounts: ["YPLQpjffJ7LS4sgHr", "mwpL9BNukdtfXQNK6"],
 profile: {
    username: "usernam"
 }
}
```

**Comment by aldeed** [comment]
This is to be expected because `allowedAccounts` is defined as an array of objects, not an array of strings.

**Comment by Tutzen** [comment]
How am I supposed to insert data in that array then? Making the array of type [Object] is what you do in the docs as well, but since something like CollectionName.insert({arrayName: ["Value", "Value"]}) doesn't work, how would the correct command look like?

**Comment by aldeed** [comment]
`"Value"` is not an `Object`, it's a string. If that's what you're trying to insert, then your `allowedAccounts` schema should be `type: String` and delete `'allowedAccounts.$.accountId'` and `'allowedAccounts.$.authorizedBy'` from the schema.

**Comment by Tutzen** [comment]
First of all, thanks for your quick answer! I know that "Value" is a string - still, you're using exact that in your documentation:

```javascript
emails: {
        type: [Object],
        // this must be optional if you also use other login services like facebook,
        // but if you use only accounts-password, then it can be required
        optional: true
    },
    "emails.$.address": {
        type: String,
        regEx: SimpleSchema.RegEx.Email
    },
    "emails.$.verified": {
        type: Boolean
    }
```

To be more concrete: In the project I'm currently working on, we have documents that can be uploaded and that have some meta information. These meta information are things like title, author and date created at. So giving meta the type [String] would mean that we can't actually store Date and other objects inside the array. Is there absolutely no way to get a string into the array if its type is Object?

**Comment by aldeed** [comment]
I don't really understand. If you want to store objects in the array like your schema shows, then you need to insert objects, not strings. If your schema is correct, then you should be inserting objects like

```js
CollectionName.insert({
  allowedAccounts: [
    {accountId: 'Value'}
  ]
})
```

**Comment by Tutzen** [comment]
Thank you! Well, it's just been me not understanding JS correctly. Sorry for taking your time for something so trivial.

**Comment by aldeed** [comment]
OK, no problem.
