### ISSUE TITLE
reactive method getting called twice after insert()

### ISSUE THREAD

**Issue by KrishnaPG** [aldeed/meteor-collection2#211]
I have a schema and collection with autoValues. 

When an item is inserted into it, reactive methods for the collection are getting called twice, once with the original fields (exactly as supplied to the insert), and next with all the fields (including the autoValues).

````
    this.autorun(function () {
        var instances = gCollections.esChartInstances.find({ chartListItemId: selectedESChartItem._id }).fetch();

        w2ui['esChartInstancesGrid'].clear(true);
        w2ui['esChartInstancesGrid'].add(instances);
        console.log("autorun: w2ui.add @" + Date.now(), instances);
    });
````

The problem is: for each reactive update, I have to do a very complex calculation, and hence would like to avoid the first update (where only the fields I supply are available) and wait for the update that has all the fields.

How to achieve this?  Here is the console log showing the two calls with different object fields

![image](https://cloud.githubusercontent.com/assets/4610831/7267328/f447b180-e8d6-11e4-8b81-1a1f4afcdd86.png)

**Comment by aldeed** [comment]
Maybe just check for one of the autovalue props and skip your calculation if it isn't there. This is a symptom of #62. AutoValues aren't added until on the server, so you see them after the subscription updates with the final data from the server.
