### ISSUE TITLE
unique:true is incompatible with optional: true

### ISSUE THREAD

**Issue by larspetrus** [aldeed/meteor-collection2#212]
I have Events and Rounds. Some events have a round, some don't. You **never** want two rounds for one event. 

This can't currently be expressed with `unique: true` on the `Events.roundId` field, since round-less events all have the same roundId value - `null`.

This is of course logical in a literal sense. But I think that what people want when specifying `unique:true, optional: true` is a field that needs to be unique **if it has a value**, but can always be without value.

**Comment by aldeed** [comment]
This package relies on MongoDB indexing to enforce uniqueness. I think MongoDB support for ignoring nulls would depend on this getting fixed: https://jira.mongodb.org/browse/SERVER-785

Generally I don't store nulls, and by default collection2 strips out nulls when cleaning. So if you simply make sure that property is only ever present when it has a value, then `unique: true` should work.

Alternatively, you can have a `rounds` array property on Events, and set `maxCount: 1` for it, tracking the relationship from the other direction.

**Comment by jfly** [comment]
Isn't what @larspetrus is describing called a "sparse index", which appears to be supported by mongodb: http://docs.mongodb.org/manual/core/index-sparse/#sparse-and-unique-properties?

**Comment by aldeed** [comment]
@jfly, sparse index allows key omission, but I think having it set to `null` is different. I'm not sure. Collection2 already does create a sparse index if optional is true, which is why I say it should work fine if you don't store `null` values.

**Comment by pierreozoux** [comment]
Hi,

I'm hitting the same issue, but a bit different.
I use `autoform` to populate my contacts. The `email` field is optional and should be unique.

On my dev machine, it is working as expected. On production, I get an error: `Email must be unique`.
I'm sad :/ Do you have any idea on how to investigate on that?

(Should I open an other issue?)

Thanks for your great work!
