### ISSUE TITLE
autoValue not setting null attributes on update

### ISSUE THREAD

**Issue by smothers** [aldeed/meteor-collection2#213]
```javascript
lastChangedAt: {
  type: Date,
  optional: true,
  autoValue: function() {
    if (this.isUpdate) {
      return new Date();
    }
  }  
}
```

In this example lastChangedAt will be `null` on insert if no value is provided for it.

On update the  `isUpdate` condition will evaluate, but lastChangedAt remains `null`.

When lastChangedAt is not null and the record is updated lastChangedAt will get a `new Date()` as expected.

*Why doesn't autoValue set attributes on update when they start off null?*

It will set attributes on insert.

This works as expected on both insert and update, so long as lastChangedAt is never set to null.
```javascript
lastChangedAt: {
  type: Date,
  optional: true,
  autoValue: function() {
    return new Date();
  }  
}
```

**Comment by aldeed** [comment]
It should work. You must have something else interfering. I would need to see a reproduction, or submit a pull request that adds a tiny test for this issue, and then I'll fix it.
