### ISSUE TITLE
Strange behaviour with "conditionally required fields"

### ISSUE THREAD

**Issue by TwinTailsX** [aldeed/meteor-collection2#220]
I've encountered an issue with a schema entry similar to the one below from the [documentation](https://github.com/aldeed/meteor-simple-schema#make-a-field-conditionally-required):
```
 {
   field: {
    type: String,
    optional: true,
    custom: function () {
      var customCondition = this.field('saleType').value == 1;
      if (customCondition && !this.isSet && (!this.operator || (this.value === null || this.value === ""))) {
        return "required";
      }
    }
  } 
 }
```

Without `!this.isSet`, an exception is being thrown with message "Error: field is required"
Though the problem is I don't want to be able to update and remove the field... Will this check be affected by update operations?

**Comment by aldeed** [comment]
`isSet` means whether the document (for an insert) or the modifier (for an update) is trying to do something to the "field" property.

So the example seems to be for checking on insert only. For an update, I think this would work, but modifiers get tricky because you have to make sure to account for all supported operators for your version of mongo.

```js
function () {
  var shouldBeRequired = this.field('saleType').value == 1;

  if (shouldBeRequired) {
    // inserts
    if (!this.operator) {
      if (!this.isSet || this.value === null || this.value === "") return "required";
    }

    // updates
    else if (this.isSet) {
      if (this.operator === "$set" && this.value === null || this.value === "") return "required";
      if (this.operator === "$unset") return "required";
      if (this.operator === "$rename") return "required";
    }
  }
}
```
