### ISSUE TITLE
Problem with "collection-hooks" when validation error?

### ISSUE THREAD

**Issue by thearabbit** [aldeed/meteor-collection2#226]
I use collection2, simpleSchema and autoform, and then I add collection-hooks.
I want to track events when collection is inserted or updated like this (in client):
```js
Collection.Customer.before.insert(function (userId, doc) {
    Events.trackInsert({
        description: doc
    });
});

Collection.Customer.before.update(function (userId, doc, fieldNames, modifier, options) {
    Events.trackUpdate({
        description: modifier
    });
});
```
When autoform have error (validation) to insert, the collection hooks still run befor....
And then I tried use after... of collection hooks, but have the same problem. 
please help me.

**Comment by matb33** [comment]
Not sure if this will do the trick, but try re-ordering `matb33:collection-hooks` within the `.meteor/packages` file, either before or after the reference to collection2

**Comment by thearabbit** [comment]
Now It work fine.
But now I found the problem is on `before.insert() and after.insert()` run both when I insert data only.
Please help me.

**Comment by aldeed** [comment]
I'm not sure I understand the new issue. Please submit a new github issue if it's still a problem.
