### ISSUE TITLE
Can I create a unique, sparse, 2d index?

### ISSUE THREAD

**Issue by chmac** [aldeed/meteor-collection2#229]
Firstly, thanks again for this excellent package, it's a huge contribution to the meteor community.

I read the part about indexes in the readme file. I've also been reading [the code](../blob/387e7e3abcf613118723af9f2f0652bfbbe922b1/collection2.js#L80-109). As far as I can tell, I can't create a 2d index, because if I pass something like `index: '2d'` on field `foo` then I'll end up with the following call:

    ensureIndex(self, {foo: '2d'}, indexName, true, false);

But to create a `2d` index I think I need to pass something like `{foo: 1, bar: 1}` as the second parameter above.

The logic to set `sparse` is `var sparse = !!definition.optional && unique;` which would allow me to mark a field as `unique: true` and `optional: true` and then get a sparse index, which is awesome.

I might well be missing something here. Figured it was smarter to ask the question of the expert than assume I was reading the code correctly. :-) Thanks in advance for any advice.

**Comment by aldeed** [comment]
Correct, you would have to use `collection._ensureIndex` directly or do the command in mongo shell.

**Comment by b1rdex** [comment]
@aldeed haven't you mind moving `index` section to `Collection` level and not field? That would cover this case and make it more simplier to read and understand.

@chmac consider moving to GeoJSON and 2dsphere. I have such field with index through SimpleSchema.
