### ISSUE TITLE
See doc before autoValue added in allow / deny rules

### ISSUE THREAD

**Issue by smothers** [aldeed/meteor-collection2#230]
I'd like to do the following:

```javascript
// Client
Posts.insert({ title: "foo" })

// Server
Posts.allow({
  insert: function(userId, doc) {
    console.log(_.keys(doc));
    // ['title', 'userId', 'createdAt', '_id']
    // I only want title, not the defaultValues
    return _.without(_.keys(doc), 'title').length === 0;
  },
});
```

The problem is that I'm also setting a bunch of default values like createdAt and userId with collection 2. They are showing up in the allow rule and causing it to fail even though the client never touched those fields.

How do I see only the client submitted values in the allow / deny rules?

I've tried adding `transform: null` but that only removes `_id` from the doc
```javascript
Posts.allow({
  insert: function(userId, doc) {
    return _.without(_.keys(doc), 'title').length === 0;
  },
  transform: null,
});
```

An alternative solution would be a way to return all the nice collection 2 error messages from a meteor method so I don't need to use allow / deny rules.

**Comment by aldeed** [comment]
1. I am not positive, but if you define your allow/deny before calling `attachSchema`, it might call them with the pre-autoValue document.
2. In the next release, the nice errors should end up back on the client, stringified on `error.details`, so you can do something like this back on the client: `var invalidKeysFromServer = JSON.parse(error.details);` and even set them into your validation context on the client if you want: `context.addInvalidKeys(invalidKeysFromServer);`
