### ISSUE TITLE
How to remove schema once added

### ISSUE THREAD

**Issue by sferoze** [aldeed/meteor-collection2#231]
Hello,

I've added a basic schema like so:

```
Schemas = {}

Schemas.Family = new SimpleSchema(
  adults:
    type: [Object]
  "adults.$.userId": 
    type: String
  children:
    type: [Object]
  "children.$.userId": 
    type: String
  createdBy:
    type: String
  test:
    type: Boolean
)

Families.attachSchema(Schemas.Family);
```
But when I comment out the attachSchema method, the schema is still attached to the collection. How do I remove a schema that was previously attached to a collection?

**Comment by cramhead** [comment]
Have you tried the replace true parameter, e.g. COLLECTION_NAME.attachSchema(SCHEMA_OBJECT, {replace: true})

**Comment by aldeed** [comment]
`delete Families._c2` should work, but indexes will stay unless you manually drop them.
