### ISSUE TITLE
cant pass by update with upsert:true,multi:true,validate:false ?

### ISSUE THREAD

**Issue by carrot93** [aldeed/meteor-collection2#232]
posts.coffee, client or server
```
Posts.update {},{$set:{temp_checked:false}},{multi:true,upsert:true,validate:false},(error,result) ->
      console.log error||result
```
TypeError, boolean is not a function or other, like: ,{multi:true},{upsert:true},{validate:false}....

I dn't want to remove attachSchema, autoform need it. But I need update some fields at temp. time.

any idea?

**Comment by steve-ross** [comment]
We have the same problem using Collection2 in a migration. It would be nice to 'detach' the schema if you were on the server side just so you can run your migration.

We just did this which his horribly non performant:

```
    Thing.find({}).forEach(function(thing){
      thing.update({},{$rename : {'this' : 'that'}},{validate: false});
    });

```

**Comment by aldeed** [comment]
I can't reproduce this. If the field you're modifying isn't in your schema, you would also have to add the `filter: false` option since cleaning and autoValues still happen even if validation does not.

Otherwise please post a link to a simple reproduction app repo.
