### ISSUE TITLE
If `optional: true` on sub-schema, just make it nullable?

### ISSUE THREAD

**Issue by AlexFrazer** [aldeed/meteor-collection2#233]
There is a schema example on the README.md that shows the Schemas.UserProfile collection. However, it seems `optional: true` is set on every attribute.

Let's say I wanted a field which could be null, OR must match the schema if it is provided.

```
AdminSchema = new SimpleSchema({
  name: { type: String }
});
Meteor.users.attachSchema(new SimpleSchema({
  // snipped out
  "profiles": {
    type: Object
  },
  "profiles.admin": {
    type: AdminSchema,
    optional: true,
    defaultValue: null
  }
}));
```

When I try to insert the following document, it gives me an error.

```
Accounts.createUser({
  email: "fake@fake.org",
  password: "passypass"
});

======
Error: Name is required
```

so if the `insertDoc` or `updateDoc` contains a key within `profiles.admin`, I want to validate it against AdminSchema, but not otherwise. Is this possible?

**Comment by aldeed** [comment]
The way you describe is the way it works. Required are only required if the object they're in is present. If this is still an issue for you, please provide a link to a simple reproduction app repo.
