### ISSUE TITLE
 Collection-Hook run all of “before.insert(), before.update()” when I “insert” data in autoform?

### ISSUE THREAD

**Issue by thearabbit** [aldeed/meteor-collection2#236]
I use collecion2, simple schema, auto form and collection-hook.
```js
// Server
Customer.before.insert(function (userId, doc) {
    console.log('before insert');
});
Customer.before.update(function (userId, doc, fieldNames, modifier, options) {
    console.log('before update');
});

// Result after inserted
before insert
before update
```
Collection-Hook run all of before.insert(), before.update() when I insert data in autoform.
Please help me.

**Comment by aldeed** [comment]
If this is still an issue, please post in the autoform repo instead.

**Comment by yogiben** [comment]
@aldeed this seems like a collection2 issue.

(I'm having it without using autoform)

https://github.com/matb33/meteor-collection-hooks/issues/167

It's frustrating, because often one wants to use the `before.insert` method to get the document ready for the `SimpleSchema` validation.
