### ISSUE TITLE
Package load error: "Tabular.Table options must specify collection" 

### ISSUE THREAD

**Issue by brylie** [aldeed/meteor-collection2#238]
When using collection2 in conjunction with `aldeed:tabular` and `matb33:collection-hooks`, users are reporting the following error:

```
Error: Tabular.Table options must specify collection
     at new Tabular.Table (packages/aldeed:tabular/common.js:20:1)
     at packages/yogiben:admin/lib/both/startup.coffee:100:27
     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
     at adminCreateTables (packages/yogiben:admin/lib/both/startup.coffee:77:4)
     at __coffeescriptShare (packages/yogiben:admin/lib/both/startup.coffee:178:2)
     at /home/.../.meteor/local/build/programs/server/boot.js:229:5
```

There is one solution posted on the [yogiben:meteor-admin #216](https://github.com/yogiben/meteor-admin/issues/216). It seems that editing the `.meteor/packages` file and moving `matb33:collection-hooks` directly below `aldeed:collection2` resolves the issue. The underlying cause is still under question.

Related issues, for discussion:
* [matb33:meteor-collection-hooks #133](https://github.com/matb33/meteor-collection-hooks/issues/133)
* [yogiben:meteor-admin #226](https://github.com/yogiben/meteor-admin/issues/226)
* [aldeed:meteor-tabular #170](https://github.com/aldeed/meteor-tabular/issues/170)

**Comment by brylie** [comment]
I have posted an issue describing the [load order of the 'comments' and 'collection-hooks' packages in yogiben:meteor-starter](https://github.com/yogiben/meteor-starter/issues/84) that may be the underlying cause of this issue.

**Comment by aldeed** [comment]
I don't think this is related to c2 or tabular. See the description here for underlying cause: https://github.com/vsivsi/meteor-job-collection/issues/58#issuecomment-72272402

Ideally the core mongo/minimongo packages should provide hooks to solve this.

**Comment by rfines** [comment]
Any idea why this error would only show up in IE 10 and below? If i change it to IE to run on the Edge version I don't see this error but any other version and this error prevents the page from loading.

**Comment by leducqui** [comment]
@rfines I meet same issue

**Comment by brylie** [comment]
@rfines and @leducqui check the order of packages that are included in your project. Our solution was to reorder the text file, as silly as that seemed.
