### ISSUE TITLE
What's the appropriate way to use Collection2 with CollectionFS ?

### ISSUE THREAD

**Issue by ShawnOceanHu** [aldeed/meteor-collection2#239]
Hi guys,
I'm using CollectionFS to store my pictures, and thinking providing references to the pictures in the normal document collections, but I'm not quite sure what's the proper way to handle this ? As I didn't find some detailed documentations on how to use them together, maybe missed something : )

So can you guys give me some hints on this ? And also provide some Guides on this topic, maybe...

Thanks :)

**Comment by AlexFrazer** [comment]
[Add the following to your project](https://github.com/yogiben/meteor-autoform-file)

**Comment by ShawnOceanHu** [comment]
I just figured out, simply store a FS.File reference to normal collections is fine ~

**Comment by afrantz** [comment]
Hey guys,

Is there a way to do think like that with Collection2 and CollectionFS for validation ?

```
const filesStore = new FS.Store.GridFS("Files", {path: "~/uploads"});

const Files = new FS.Collection("Files", {
  stores: [filesStore]
});

const MySchema = new SimpleSchema({
  file: {
      type: File,
      optional: true
  }
});
```

If I put "type: File" in order to reference File Collection, when I run meteor, I got : 
```
W20151210-16:35:27.386(1)? (STDERR) /home/alex/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151210-16:35:27.386(1)? (STDERR)                                             throw(ex);
W20151210-16:35:27.386(1)? (STDERR)                                                   ^
W20151210-16:35:27.387(1)? (STDERR) RangeError: Maximum call stack size exceeded
```

Thanks !
