### ISSUE TITLE
Array of arrays of objects

### ISSUE THREAD

**Issue by Adam-Goldman7** [aldeed/meteor-collection2#244]
Data format:

```js
turns: [
  [
    { 
      comments: [
        {}
      ]
    }
  ]
]
```

I've tried this:

```
turns: {  type: [[Object]]   } 
"turns.$.$": { type: Object }
"turns.$.$.user_id": { type: String }
```

and I get this:

SimpleSchema.clean: filtered out value that would have affected key "turns.$.0.user_id", which is not allowed by the schema

What am I missing here?

Thanks in advance! :)

**Comment by aldeed** [comment]
I don't know if `[[Object]]` will parse correctly. Better to spell it all out.

```js
turns: {  type: Array   }
"turns.$": { type: Array } 
"turns.$.$": { type: Object }
"turns.$.$.user_id": { type: String }
```

If you are still having trouble please post in simple-schema repo and reference this issue, since this is a SS question/issue.
