### ISSUE TITLE
Update $pull on Subcollection-Array doesn't work with collection2

### ISSUE THREAD

**Issue by h2s20** [aldeed/meteor-collection2#245]
I have a collection Member with an embedded array Fee as subcollection. One Member can have multiple Fees. 
If I try to pull a Fee from the array the update function succeeds but nothing happens. The array doesn't get pulled from the array.
I think the problem lies with collection2 because if I use the update function from the mongo shell everythink works fine and if remove collectio2 it also works fine.

The reproduction can be found here on meteorpad: http://meteorpad.com/pad/uE7dmsXgianEB2Ea5/Pull-Subcollection-Array
If you comment out line 52 in common.js - it's possible to remove an object from the array
If you don't comment out line 52 in common.js - the callback of the update function is successfull but nothing happens.

```javascript
//Members.attachSchema(Schemas.Members);
```

* Am I using collection2 the wrong way or is this a bug?
* Is there a possible workaround?

The schema:
```javascript
Members = new Meteor.Collection('members');
var Schemas = {}
Schemas.Members = new SimpleSchema({ 
    fn: {
        type: String,
        label: "Firstname",
        max: 30
    },
    ln: {
        type: String,
        label: "Lastname",
        max: 30
    },
    fee: {
        type: Array,
        optional: true,
    },
        'fee.$': {
            type: Object
        },
        'fee.$._id': {
            type: String,
            autoValue: function(){
                return Random.id();
            },
            optional: false
        },
        'fee.$.amount': {
          type: String,
          label: "Amount",
          optional: true
        },
});
//Comment out the next line and the $pull of the subcollection will work
Members.attachSchema(Schemas.Members);
```

on the client:
```javascript
Template.latestFee.helpers({    
    subCollection: function () {        
        f = Members.findOne({_id: "n6EzuD6tc5Ng66MKR"});
        //only return Subcollection
        return f.fee;
    },
});

Template.latestFee.events({
    'click button.remove-fee': function (evt) {
        evt.preventDefault();
        var subIndex = evt.currentTarget.getAttribute('data-index');
        Meteor.call("removeSub", "n6EzuD6tc5Ng66MKR", subIndex)
}})
```

method on the server
```javascript
Meteor.methods({
    removeSub: function (memberID, subID) {
        console.log("MemberID: " + memberID + " | " + "SubID: " + subID);
        Members.update(
            {_id: memberID},
            {$pull:{fee: {_id: subID}}

            });
    }
});
```

**Comment by h2s20** [comment]
The following option-argument in the update function solves the problem:  {getAutoValues: false}
```javascript
Meteor.methods({
    removeSub: function (memberID, subID) {
        console.log("MemberID: " + memberID + " | " + "SubID: " + subID);
        Members.update(
            {_id: memberID},
            {$pull:{fee: {_id: subID}}}, {getAutoValues: false});
    }
});
```

It skips the generation of autovalues which is no problem in this case as I want to remove the objects but I think this might lead to a new problem if you want to modify the values of the subdocument.

**Comment by aldeed** [comment]
It's debatable whether it should be calling autoValue functions when the operator is `$pull`, but currently it does. So I think you could fix this by adding this as the first line of your autoValue:

```js
if (this.operator === '$pull') return;
```

**Comment by TimFletcher** [comment]
When logging `this.operator` from inside my `campaigns` array `autoValue` I'm seeing `$set` rather than `$pull` for the following query:

```
Leads.update(
  { _id: leadId }},
  { $pull: {campaigns: { campaignId: campaignId }}},
  { multi: true }
);
```

Adding `getAutoValues: false` to the final options object does provide a workaround though. Thanks @h2s20!

**Comment by cdolek** [comment]
Thanks @h2s20 you saved me lots of time! "{ getAutoValues: false }" works.

@aldeed *"if (this.operator === '$pull') return;"* did not work. I am using aldeed:collection2@2.9.1, aldeed:simple-schema@1.5.3 | Many thanks for the great packages!

**Comment by diegodelfin7** [comment]
Thanks @h2s20 ! same issue.

**Comment by Paku-** [comment]
For me `if (this.operator === '$pull') return;` nor  `getAutoValues: false` work using AutoForm 6.
Any other suggestion as of end of 2017 ??
