### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by shactdeveloper** [aldeed/meteor-collection2#246]
Hello, im trying to implement relationships with this code:
Manufacturers = new Mongo.Collection('manufacturers');
Manufacturers.attachSchema(new SimpleSchema({
    name: {
      type: String
    }	
}));

Colors = new Mongo.Collection('colors');
Colors.attachSchema(new SimpleSchema({
    name: {
      type: String
    }
}));

Cars = new Mongo.Collection('car');
Cars.attachSchema(new SimpleSchema({
    manufacturer: {
      type: Manufacturers
    },
    color: {
      type: Colors,
      optional: true
    }	
}));

and I'm having this error:

/home/rafa93br/.meteor/packages/meteor-tool/.1.1.4.p2mczn++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
RangeError: Maximum call stack size exceeded
Exited with code: 8
Your application is crashing. Waiting for file change.

Am I'm doing something wrong? :(

**Comment by serkandurusoy** [comment]
You are referencing other *collections* in your type definition. But you should be referencing *schemas*.

```javascript
Manufacturers = new Mongo.Collection('manufacturers');
Manufacturers.Schema = new SimpleSchema({
  name: {
    type: String
  }
});
Manufacturers.attachSchema(Manufacturers.Schema);

Colors = new Mongo.Collection('colors');
Colors.Schema = new SimpleSchema({
  name: {
    type: String
  }
});
Colors.attachSchema(Colors.Schema);

Cars = new Mongo.Collection('car');
Cars.Schema = new SimpleSchema({
  manufacturer: {
    type: Manufacturers.Schema
  },
  color: {
    type: Colors.Schema,
    optional: true
  }
});
Cars.attachSchema(Cars.Schema);
```

**Comment by shactdeveloper** [comment]
But my mind is still clouded about some things
When you create an field with type equals another schema, you are creating a field that contains an entire document of the another collection, right? thats not what i want.. i want just to store a reference id... not duplicate the referenced document every time

**Comment by shactdeveloper** [comment]
obviously i could just create a field with type String and store the other document Id, but then it`s not a relationship behavior, its just a string store

**Comment by serkandurusoy** [comment]
A reference to another schema means that that part of the document structure within a single document must conform to the schema rules that are proposed by the referenced schema.

Schema definitions are applied per document.

So it is like embedding a single document within a field of the single parent document. So it is not a "join" type relationship, nor a reference. It does not facilitate nor provides a context for a relationship.

A relationship is what you can achieve by setting the type to string and storing the referenced document's id. So with a second database call, you can fetch the referenced document.

Or if you want to reference mutiple documents, make it a [String] type and reference multiple id's.

So as you said it it sill is not a *formal sql world type of relationship* but *mongodb is not a relational database* so perhaps you should first brush up on your mongodb skills which will put the meteor side of things into more perspective for you.

For further discussion about relationships and joins in meteor, [search the forum](https://forums.meteor.com/) where there's loads of information and examples.

**Comment by aldeed** [comment]
There is a design for implementing pseudo-relationship support through collection2 similar to how you're trying to do it, but that is not currently a feature. You need to store the string ID and do your own joins as @serkandurusoy said. If in publication, then use one of the reactive join packages.

**Comment by shactdeveloper** [comment]
Now everything is clear to me! Thanks guys
