### ISSUE TITLE
Collection2 and Simple-Schema seem to complicate testing with Velocity and Jasmine

### ISSUE THREAD

**Issue by dpneumo** [aldeed/meteor-collection2#249]
A test to check that schema defined validation requirement catches an invalid document on insert always fails with a message indicating a validation failure. The test is intended to pass if the invalid document is caught.

    Error: Subj is required
    packages/aldeed:collection2/collection2.js:369:1: Error: Subj is required
      at getErrorObject (packages/aldeed:collection2/collection2.js:369:1)
      at [object Object].doValidate (packages/aldeed:collection2/collection2.js:352:1)
      at [object Object].Mongo.Collection. (anonymous function) [as insert] (packages/aldeed:collection2/collection2.js:154:1)
      at app\tests\jasmine\server\integration\pftDataModelSpec.js:8:18

The Server Integration tests used:

    "use strict";
    describe("PFTs", function(){
      it("must be created with subjId set", function(){
        var invalidNewPFT = {};
        expect( PFTs.insert(invalidNewPFT) ).toThrow();
      });
    });

The question of how to test this was posed on StackOverflow. @Sanjo recommended I use:

    expect(function () { PFTs.insert(invalidNewPFT); }).toThrow();

This still failed with the same message indicating that validation failed. Based on that recommendation I found this code does work to achieve my testing goals:

    "use strict";
    describe("PFTs", function(){
      it("cannot be created without a subjId", function(){
        var testDate = new Date();
        var invalidNewPFT =   {pftDate: testDate}
        var preinsertCount = PFTs.find().fetch().length;

        // expect used here to swallow the msg sent to the browser by Collection2
        expect( function(){ PFTs.insert(invalidNewPFT); }).toThrow;

        // Verify that a record was not saved
        expect( PFTs.find().fetch().length ).toEqual(preinsertCount);
      });
    });

However, it does not matter whether I use .toThrow or .not.toThrow in the first expect. It appears that Collection2 is swallowing the error generated by attempting to insert an invalid record. Perhaps this occurs by submitting the insert within Collection2 with a callback added that captures the error or perhaps the call to insert is never made. In any event it is necessary to step around this by checking for an increment in the number of documents in the collection after the insert is attempted. This only means two extra lines of code. However, it is a little ugly to have to do this and also it was not obvious that I could use expect to swallow the message from Collection2. Without that step the actual check for a document count increase would never occur.

It might be appropriate to either document this behavior or to provide a mechanism to allow the validation failure to flow out to the testing harness in a manner that is easily testable using standard Jasmine matchers.  

Context: 

    Windows 7
    meteor@1.1.6
    aldeed:autoform@5.4.0
    aldeed:collection2@2.3.3
    aldeed:simple-schema@1.3.3
    velocity:core@0.9.3
    sanjo:jasmine@0.16.4

Requirements:

    1. Pulmonary Function test results (PFTs) are stored.
    2. A pft document must contain a date (pftDate) and a Subject Id (subjId).

Schema:

    PFTs = new Meteor.Collection('pfts');

    Schema = {};
    Schema.PFTs =  new SimpleSchema({
      subjId: {
        type: String,
        autoform: {
          type: "hidden",
          label: false,
        },
      },
      pftDate: {
        type: Date,
        label: 'Date',
        max: function(){ return new Date() },
      },
    });

    PFTs.attachSchema(Schema.PFTs);

**Comment by dpneumo** [comment]
Well actually wrapping the PFTs.insert(document) in an expect appears to suppress insertion of the document in Mongo in addition to suppressing the error message from Collection2. So testing for failure to insert a document using the method described above simply tests the effects of the wrap and NOT the desired behavior of my schema. Thus at the moment I am unable to see a way to do testing that my schema meets project requirements.

Here are the tests to document the effect of the wrap:

    "use strict";
    describe("A PFT", function(){

      // Succeeds
      it("can be created with both subjId and pftDate set", function(){
        var testDate = new Date();
        var validNewPFT =   {pftDate: testDate, subjId: '1'}
        var preinsertCount = PFTs.find().fetch().length;
        PFTs.insert(validNewPFT);

        expect( PFTs.find().fetch().length ).toEqual(preinsertCount+1);
      });

      // Fails the count test
      it("is created when insert is wrapped in an expect", function(){
        var testDate = new Date();
        var validNewPFT =   {pftDate: testDate, subjId: '1'}
        var preinsertCount = PFTs.find().fetch().length;
        expect( function(){ PFTs.insert(validNewPFT); }).not.toThrow;

        expect( PFTs.find().fetch().length ).toEqual(preinsertCount+1);
      });

      // Fails with error msg from Collection2
      it("cannot be tested with an unwrapped insert - 1", function(){
        var testDate = new Date();
        var invalidNewPFT =   {pftDate: testDate}
        var preinsertCount = PFTs.find().fetch().length;
        PFTs.insert(invalidNewPFT);

        expect( PFTs.find().fetch().length ).toEqual(preinsertCount);
      });

      // Also fails with error msg from Collection2
      it("cannot be tested with an unwrapped insert - 2", function(){
        var testDate = new Date();
        var invalidNewPFT =   {pftDate: testDate}
        var preinsertCount = PFTs.find().fetch().length;
        PFTs.insert(invalidNewPFT);

        expect( PFTs.find().fetch().length ).toEqual(preinsertCount+1);
      });
    });

**Comment by Sanjo** [comment]
May you could test it like this:

1. Test that the collection has the schema assigned
2. Test the validation of data directly with the Simple Schema (Schema.PFTs)

I think the other test concerns should be tests in the collections2 package.

**Comment by dpneumo** [comment]
Yes. That seems to work well. Testing the schema directly avoids the C2 effects. I do not know a way to directly ask a collection for the name of an attached schema so I resorted to asking for the keys of the schema and verifying that the keys of interest are included.

    "use strict";
    describe("The PFT Schema", function(){

      it("contains keys for subjId and pftDate", function(){
      var schemaKeys = PFTs._c2._simpleSchema._firstLevelSchemaKeys;
      expect(schemaKeys).toContain('subjId');
      expect(schemaKeys).toContain('pftDate');
      });

      describe("context", function(){
        var ssPFTContext = Schema.PFTs.namedContext("pft");

        it("requires the presence of subjId & pftDate", function(){
          var validPFTData = {subjId: 1, pftDate: new Date()};
          expect( ssPFTContext.validate(validPFTData) ).toBeTrue;
        });

        it("fails if subjId is absent", function(){
          var invalidPFTData = {pftDate: new Date()};
          expect( ssPFTContext.validate(invalidPFTData) ).toBeFalse;
        });

        it("fails if pftDate is absent", function(){
          var invalidPFTData = {subjId: 1};
          expect( ssPFTContext.validate(invalidPFTData) ).toBeFalse;
        });
      });
    });

Thanks once again.
