### ISSUE TITLE
Using example user schema leads to loginWith<service> failed.

### ISSUE THREAD

**Issue by zhaoyao91** [aldeed/meteor-collection2#254]
I get the error `Exception while invoking method 'login' Error: Username is required`.

Logining with 3rd part service seems don't need username. Maybe the schema should be updated to make username filed optional.

**Comment by derwaldgeist** [comment]
+1
Ran into the same problem. I am using the meteor-useraccounts package, and the problem even occurs if you log-in with email and password (there is no username involved here, either). Would also recommend to set the username field to optional in the sample.

**Comment by derwaldgeist** [comment]
Thanks for fixing this!

**Comment by zhaoyao91** [comment]
Thanks!
