### ISSUE TITLE
Sample user schema: RegEx not really useful for other languages than English

### ISSUE THREAD

**Issue by derwaldgeist** [aldeed/meteor-collection2#256]
The sample user schema uses this RegEx like these
```
regEx: /^[a-zA-Z-]{2,25}$/
```
to check username, firstName, lastName and other properties. This may work for English users, but does not take into account that there are language out there which are using an extended character set. I know that this schema is just meant as an example, but I would change this to something more usable. 

Besides that, there are languages where the characters "-" and " " (blank) may appear in first names and last names, e.g. in German or Spanish. So I would like to recommend to add these characters to these languages as well.

I also noticed that the RegEx for Organization field contains an error (z instead of Z).

**Comment by aldeed** [comment]
I don't know where those expressions came from anyway, and they aren't necessary, so I removed them. Thanks.

**Comment by derwaldgeist** [comment]
Perfect, that's also a good option!
