### ISSUE TITLE
Inheritance

### ISSUE THREAD

**Issue by merlinpatt** [aldeed/meteor-collection2#257]
I looked through the docs but couldn't seem to find it. Is there anything like inheritance?

Let's say I create simple collection of categories with names, types, and various metrics like number of users per category, number of posts per category, etc.

    Schemas.Category = new SimpleSchema(
        name: ...
        type: ...
        userCount: ...
        postCount: ...
    )}

But then I want a certain type of category, say animals, to have extra properties like genus.

I could make this a [conditionally required field](https://github.com/aldeed/meteor-simple-schema#make-a-field-conditionally-required) but that seems a little messy for something that will only appear on a small fraction of categories.

Instead, I'd prefer to to do something like this.

    Schemas.Animals = new SimpleSchema({
        extend: Schemas.Category,
        genus: ...
    )}

Is this possible?

**Comment by aldeed** [comment]
See https://github.com/aldeed/meteor-simple-schema#combining-simpleschemas

Pass array of schemas to be combined to `SimpleSchema` constructor.

**Comment by merlinpatt** [comment]
How do I attach that extended Schema to the same collection?

What I'm trying to do is make it clear that certain subsets will have required types but they're all on the same categories collection.

I'd rather have `Schemas.Category`, `Schemas.Animal`, `Schemas.Hardware`, `Schemas.Company` so it's clear what each field belongs to and what fields belong to the superset.

Then I'd like to have them all attached to that one category collection

**Comment by aldeed** [comment]
You can't. You would need multiple collections. For same collection, you'll need custom conditional logic like you said.
