### ISSUE TITLE
Question - using relational keys for inserts

### ISSUE THREAD

**Issue by methodbox** [aldeed/meteor-collection2#260]
I apologize ahead of time if I'm not asking this correctly.

I have a Meteor app that is basically a form that submits a survey.  The relationship can be thought of as a person and a family member.

I want to be able to re-use the person and family member so that they are not added as new entries each time the form is submitted, but so that the rest of the data submitted can be added as a unique entry.

So basically there's a name, second name that need to be entered once and never again, but will have multiple objects like this:

```
{
   date: '9/25/2015',
   time: '9:00PM',
   notes: 'Lorem ipsum blah blah'
}
```
I'm trying to determine if I can use this package to define a schema that would result in being able to associate new records with a name/secondary name, kind of like the "books" example if you had an ```authorLastName``` and ```authorFirstName``` that would remain once entered but new books that could be added later. Obviously I need to check that the name does/does not exist first, but I need to be able to add new entries associated w/that key/ID.

Any assistance would be appreciated!

**Comment by aldeed** [comment]
I think your schema would have `firstName`, `lastName`, and an `entries` property that is an array of objects. Then your form would just have the entries fields (date, time, notes), and when it is submitted, it would do an `update` with `$push` to add the entry to the `entries` array for whatever name is being edited.

**Comment by methodbox** [comment]
Awesome! Thank you so much man.  I always forget about push.

It's like ```this``` where sometimes it has unexpected behaviour.

But yeah that's pretty straightforward. I'll test this out later today.
