### ISSUE TITLE
update(doc, {$set: {object_field: {...}}}) doesn't work with type Object

### ISSUE THREAD

**Issue by vonwao** [aldeed/meteor-collection2#262]
When I attach a schema to a Collection with field of type: Object, and I update doc like this:

    Coll.update(doc, {$set: {object_field: {test: "test value"}}})

I'm expecting to get this: 
{"_id":"Zw7gEH2JkuaSAnwJr","title":"Introducing Telescope","object_field":{"test":"test value"}}

But I get this:
{"_id":"Zw7gEH2JkuaSAnwJr","title":"Introducing Telescope","object_field":{}}

This behavior seems wrong (otherwise, what's the correct way to specify schema?).  

Here is my full test case.

```
Coll = new Mongo.Collection('coll');
Coll.attachSchema(new SimpleSchema({
  title: {
    type: String
  },
  object_field: {
    type: Object,
    optional: true
  }
}));

Meteor.methods({
  updateTest: function() {
    var doc = Coll.findOne({}, { sort: { title: -1 }});
    Coll.update(doc, {$set: {object_field: {test: "test value"}}})
  }
})
```

**Comment by merlinpatt** [comment]
I may have a related bug except with a nested array. And when I try to do a `$push` operation

`Meteor.users.update({_id: Meteor.userId()}, {$push: {'nestArray.0': 'test'}})`

I get the error: `Uncaught TypeError: Cannot read property 'blackbox' of undefined` triggered by the line `if (self.schema(schemaKey).blackbox === true) {` in `SimpleSchema.prototype.allowsKey`

Here is my abridged schema

```
NestArray = new SimpleSchema({
  0: {
    type: [String],
    defaultValue: [],
  },
  '0.$': {
    type: String,
    regEx: SimpleSchema.RegEx.Id,
  },
  ...
});

User = new SimpleSchema({
  nestArray: {
    type: NestArray,
  },
  ...
});
```

**Comment by merlinpatt** [comment]
So after digging into the code further, my issue is that any numeric object keys get auto converted into `$` signs. Is there any way around this without changing to a 2D array?

**Comment by aldeed** [comment]
@vonwao Add `blackbox: true` to `object_field` schema, or define `test` property in the schema.

@merlinpatt I don't think number keys are currently supported. 2d array or use `zero.$` or something
