### ISSUE TITLE
Meteor 1.2.0.2 - mongo error when using index

### ISSUE THREAD

**Issue by PhilippSpo** [aldeed/meteor-collection2#263]
I just updated to Meteor 1.2.0.2 and am getting the following error:
```
MongoError: Index with pattern: { name: 1 } already exists with different options
```
It worked with 1.2.0.1 ...
I looked in the History.md what happened for 1.2.0.2 but there is nothing that would be related to this. Probably something under the hood is happening here.
This is where the error occurs:
```
at [object Object].MongoConnection._ensureIndex (packages/mongo/mongo_driver.js:790:1)
at packages/aldeed_collection2/packages/aldeed_collection2.js:77:1
```

**Comment by pdelasotta** [comment]
Could you please tell me how you fixed it?

**Comment by luki3k5** [comment]
I am having similar problem right now - please share how you fixed it, thanks!

**Comment by florasolutions** [comment]
Same here! Please share.
