### ISSUE TITLE
Is autovalue can possibly grab a user profile?

### ISSUE THREAD

**Issue by Ajaxsoap** [aldeed/meteor-collection2#265]
Hi @aldeed ,

Is autovalue can grab user profile? 

Ex. I have a collection with a schema and i want to grab users profile which has company and branch and store in the collection, this user is the owner of the document or the one created it. 

I haven't tried if the below snippet work:
```
company: {
    type: String,
    autoValue: function() {
      if (this.isInsert) {
        var user = Meteor.users.findOne({ "_id": this.userId }, { fields: { "profile": 1 } });
        return user && user.profile.company
      } else {
        this.unset();  // Prevent user from supplying their own value
      }
    }
  },
```
What is your recommendation on grabbing user profile?

Thanks.

**Comment by aldeed** [comment]
Yes autoValue runs on the server, and looking up data from other collections in the function is fine.

**Comment by c316** [comment]
@aldeed The documentation says that the userId field will be ```null``` on the server...

https://github.com/aldeed/meteor-collection2#autovalue
