### ISSUE TITLE
validation always passes after transform, e.g. with dburles:collection-helpers

### ISSUE THREAD

**Issue by thomasspiesser** [aldeed/meteor-collection2#269]
hey,
I use collection2 for validation but since I added dburles:collection-helpers validation always passes even though required fields are missing. 

[Here](https://github.com/thomasspiesser/c2-collection-helper-bug-repro) is a clean repo to illustrate my case. 
Without the collection helper I get:

```
I20151013-20:49:40.561(2)? { _id: 'JzGEr72QGvsDofvKr',
I20151013-20:49:40.561(2)?   title: 'test-course',
I20151013-20:49:40.561(2)?   owner: 'this.userId',
I20151013-20:49:40.561(2)?   ownerName: 'someone',
I20151013-20:49:40.561(2)?   createdAt: Tue Oct 13 2015 20:49:40 GMT+0200 (CEST) }
I20151013-20:49:40.562(2)? false
I20151013-20:49:40.562(2)? [ { name: '_id',
I20151013-20:49:40.562(2)?     type: 'keyNotInSchema',
I20151013-20:49:40.562(2)?     value: 'JzGEr72QGvsDofvKr' } ]
```

With the collection helper I get:

```
I20151013-20:49:27.377(2)? { _id: 'hFmeFbtaDrBADSrNz',
I20151013-20:49:27.377(2)?   title: 'test-course',
I20151013-20:49:27.377(2)?   owner: 'this.userId',
I20151013-20:49:27.377(2)?   ownerName: 'someone',
I20151013-20:49:27.377(2)?   createdAt: Tue Oct 13 2015 20:49:27 GMT+0200 (CEST) }
I20151013-20:49:27.377(2)? true
I20151013-20:49:27.377(2)? []
```

Is that the intended behavior?

**Comment by thomasspiesser** [comment]
funnily enough, on the Meteor.users collection it's quite the opposite, meaning validation works, but including a collection helper (e.g. a getEmail() function) makes the validation fail with error: getEmail is not in schema.

**Comment by mgrivera** [comment]
Hi, some updates about this issue? still remains? Is there a workaround available? 
@thomasspiesser: Were you able to solve this issue? 
Thanks and bye ...

**Comment by thomasspiesser** [comment]
Nope, never solved it. But I have also not investigated any further. Sorry. Did you experience the same?

**Comment by aldeed** [comment]
Closing old issues. Please comment if this is still an issue and should be reopened.
