### ISSUE TITLE
validate: false erases document properties

### ISSUE THREAD

**Issue by SachaG** [aldeed/meteor-collection2#271]
I'm running into a pretty weird behavior, and I'm not sure if it's Collection2's fault or just something wrong with my syntax.

In the Meteor shell, if I run:

```
Collection.update('xyz', {$set: {foo: 123}})
```

With `foo` belonging to the schema, everything works. Now if I run:

```
Collection.update('xyz', {$set: {bar: 123}})
```

With `bar` *not belonging to the schema, I rightly get the `When the modifier option is true, validation object must have at least one operator` error (although in passing, I feel like that error message is pretty far off the mark. Seems a bit unrelated with what's actually going on…?)

But now if I run:

```
Collection.update('xyz', {$set: {bar: 123}}, {validate: false})
```

The update goes through, but instead of adding `bar` to my document it erases all of its properties except for the `_id`… What's going on here?

**Comment by somebee** [comment]
I'm experiencing the same thing. Hope it gets fixed soon.

**Comment by aldeed** [comment]
It currently mutates the modifier when cleaning it, and the cleaning happens before the validation. This will probably be changed in a future version, but there is already a ticket for that. #182
