### ISSUE TITLE
can i use multiple emails in Accounts.createUser using simple schema

### ISSUE THREAD

**Issue by bipin244** [aldeed/meteor-collection2#273]
i have created custom register form and enter multiple email address.
for insert i have user Accounts.createUser but its give error like this
 Exception while invoking method 'insertUser' TypeError: Cannot read property '$' of undefined
I20151019-19:48:45.710(5.5)?     at [object Object].Meteor.methods.insertUser (app/server/method/default.js:50:26)
I20151019-19:48:45.710(5.5)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20151019-19:48:45.710(5.5)?     at packages/ddp/livedata_server.js:648:1
I20151019-19:48:45.711(5.5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20151019-19:48:45.711(5.5)?     at packages/ddp/livedata_server.js:647:1
I20151019-19:48:45.711(5.5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20151019-19:48:45.711(5.5)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20151019-19:48:45.711(5.5)?     at packages/ddp/livedata_server.js:546:1

**Comment by aldeed** [comment]
I would need a full reproduction to debug this, but generally speaking, you need to make any changes to the user schema as necessary based on what your app does and what packages you use. The example in the readme is only to get you started.
