### ISSUE TITLE
AutoValue from adjacent fields, not present in the update

### ISSUE THREAD

**Issue by Pushplaybang** [aldeed/meteor-collection2#277]
Hi There

Is it at all possible to get adjacent fields values in an autovalue function that are not present in the update.

I have a `stats` object in my schema that counts up votes, down votes, favourites, comments etc and i'd like to run these through a weight calculation each time the doc is updated, (updatedAt is also being set with an autoValue field).

do these have to be passed through from the client with the update?

**Comment by aldeed** [comment]
The `autoValue`, `custom`, etc. don't do any database queries. On the server, you could do the `findOne` yourself in the function. Otherwise you can use a collection hook or do this within a server method.

**Comment by Pushplaybang** [comment]
thanks, this is what I'd expected.
