### ISSUE TITLE
Updating an array of sub-documents fails validation if the sub-documents are transformed

### ISSUE THREAD

**Issue by dcworldwide** [aldeed/meteor-collection2#281]
Not sure if i'm doing it right, I've noticed the following validation issue which i think isn't accurate.

I have a collection called A where each A document contains a property B (a transformed array of objects). I've decided to transform each B object so that i can extend its behaviour.

If i call A.update(id, {$set: {B:modifiedArray}}), validation fails because validation expects modifiedArray to be an array of POJOs and not Transformed Objects. 

The only workaround i've found so far is to specify validate: false. But this is really risky behaviour. 

Any ideas? Is it a package limitation or can i do something differently?

Thanks

**Comment by aldeed** [comment]
I think the only other solution is to transform them back. Without seeing an example of how exactly they're transformed I'm not sure. But if they don't match the schema, then they don't pass validation.
