### ISSUE TITLE
Exception while invoking method 'login' with Facebook

### ISSUE THREAD

**Issue by Almaju** [aldeed/meteor-collection2#282]
Hello,

Just to help if some people get the same error as I got: suddenly Facebook login stopped working when attaching a schema to Meteor.users.

Here is the fix:
1/ Add _id to schema : 
```
Schema.User = new SimpleSchema({
	_id: {
		type: String
	}
	...
});
```

2/ Add email within "onCreateUser" action:
```
if(user.services.facebook){
	user.emails = [{
		address: user.services.facebook.email,
		verified: true,
	}];
}
```

3/ If errors subsists, do a check(user, Schema.User) in your onCreateUser action to debug.

Cheers!

**Comment by aldeed** [comment]
Thanks for posting.
