### ISSUE TITLE
How can I get the type of the filed ?

### ISSUE THREAD

**Issue by Marcus-Crassus** [aldeed/meteor-collection2#287]
Hi there. How can I get the type of the field (String, Array, ...), if I have a global db object (Clients) ?

Clients._c2._simpleSchema._schema.image.type.name
It works, but, maybe, is there better solution (some function 'getType')?

**Comment by aldeed** [comment]
Using the public APIs it would actually be `Clients.simpleSchema().schema().image.type.name`, but yes, the next major release of simple-schema will have some nicer function for getting type and other details about a key.
