### ISSUE TITLE
Insert with 'bypassCollection2: true' throws an exception

### ISSUE THREAD

**Issue by art-reddy** [aldeed/meteor-collection2#290]
Hi!

When I insert a document like that
```
collection.insert(doc, {bypassCollection2: true})
```
I get an exception in console
```
Exception in Mongo write: TypeError: object is not a function
  at packages/mongo/mongo_driver.js:322:1
  at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
```
Document in fact is inserted successfully but I can't use callback function as a third parameter. So there is probably some mismatch when parameters are passed to original Mongo insert function.

**Comment by aldeed** [comment]
Oh, yeah, that's a bug. Need to remove the options. I will fix.
