### ISSUE TITLE
Index won't build on camelCase field

### ISSUE THREAD

**Issue by yoepus** [aldeed/meteor-collection2#294]
As part of schema:

this will fail (on meteor start; gives invalid definition error):

**someProductId**: {
            type: String,
            label: "A Product Id",
            index: 1,
            unique: true
}

this will work:

**someproductid**: {
            type: String,
            label: "A Product Id",
            index: 1,
            unique: true
}

Also this will fail:

someproductid: {
            type: String,
            label: "A Product Id",
            index: 1,
            unique: **1**
}

Not sure if this is the desired behavior (if so, perhaps a quick note in the docs) or something else...
Using most recent version pulled yesterday.

**Comment by aldeed** [comment]
`unique` must be boolean, so it makes sense the last one would fail. Camelcase would not make any difference, though. If the first one really fails as written, I'd need to see a simple reproduction app.
