### ISSUE TITLE
Request for a way to turn off default callbacks for the client side

### ISSUE THREAD

**Issue by andylash** [aldeed/meteor-collection2#298]
Hi, 

I'm working on testcases on top of the new mdg:validated-method codebase, simple-schema, and collection 2.  Over time I want to move to methods vs. allow/deny, but there's plenty to do there.  

One little problem I've found is that it's not possible to run database operations on the client synchronously at all, because of this code:

https://github.com/aldeed/meteor-collection2-core/blob/1af9384310d3e012098e9a0aeb1042d342564283/lib/collection2.js#L180-L184

I realize that in application code you'd not want to do this, but it's very convenient in test code looking at the method executions to have the errors thrown.  I can pass in a callback, but that makes these testcases all async, where they'd be much simpler as sync.  If I comment out those lines, the errors are thrown just fine.  Might there be a parameter I could pass to enable this behavior?

Happy to do the work in a PR, just not sure how you'd want to see that configured.

**Comment by andylash** [comment]
So I've got this crappy work around, but would really like to do this as a PR.  Any thoughts on how you'd want to configure this?  It's a big help for writing testcases.

**Comment by aldeed** [comment]
Closing old issues. Please comment if this is still an issue and should be reopened.
