### ISSUE TITLE
Use autoValue with a bulk write operation

### ISSUE THREAD

**Issue by cspecter** [aldeed/meteor-collection2#300]
Is it possible to use an autoValue on a key when using a bulk write operation when updating my database? I have an app that needs to write a lot of imported data every minute. Right now I have several keys that use an autoValue to set some data based on each imported document. In my attempts to speed things up I switched over to using a bulk write op, but it seems to have broken all my autoValues. I know the bulk does an direct upload to mongo, bypassing the normal insert, but it also seems to be bypassing my autoValue functions. I've tried using various combinations of insert, upsert and updates, no luck. Is there some trick to get this to work?

**Comment by aldeed** [comment]
Closing old issues. The answer is to call `schema.clean()` on each object before adding it to the bulk operation.
