### ISSUE TITLE
Question about autoValue

### ISSUE THREAD

**Issue by erdgrau** [aldeed/meteor-collection2#301]
Why If I add console.log(this.value) in function autoValue, I see double calling console.log(); on the client side? Also If I do some transforms in function autoValue, like this:

``` javascript
Schemas.Books = new SimpleSchema({
date: {
        type: Date,
        label: 'test',
        autoValue: function () {
            if(Meteor.isClient) {
                console.log('call this.value --> : ', this.value);
                console.log('call moment.toDate --> : ', moment(this.value, 'Do MMMM YYYY').toDate());
                return moment(this.value, 'Do MMMM YYYY').toDate();
            }
        }
    }
});
```
##### I have this console.log():

![tet12](https://cloud.githubusercontent.com/assets/12447113/12428176/d7918e12-beeb-11e5-9796-b68951757c71.jpg)

When the second call is, the moment has wrong parameter, because in the second call this.value has object  (this is the result of the first call of the autoValue). Do I do something wrong, maybe  ?

P.S. I know that autoValue is performed both on the client and the server.

**Comment by aldeed** [comment]
This was fixed quite awhile ago
