### ISSUE TITLE
Setting a field as `optional` doesn't behave like it should

### ISSUE THREAD

**Issue by Menda** [aldeed/meteor-collection2#303]
I have the following schema:

```
Manufacturer = new SimpleSchema({
  name: {
    type: String,
    max: 70
  },
  description: {
    type: String,
    optional: true
  }
});
```

But this test fails, and shouldn't fail because the insert should return an exception:

```
describe('Manufacturer @focus', function() {
  it('should be not inserted successfuly', function () {
      var errored = server.execute(function() {
        var insertSync = Meteor.wrapAsync(Manufacturers.insert, Manufacturers);
        try {
            insertSync({name: 'Ferrari', invented: 'made_up'});
        } catch(error) {
          return true;
        }
        return false;
      });
      assert.isTrue(errored, 'insert failed raising an exception');
  });
});
```

However if I make it mandatory and set `{name: 'Ferrari', description: 'A brand', invented: 'made_up'}` then the test passes.

It's really weird, because I tried `Manufacturers.simpleSchema().namedContext().validate(obj);` and doesn't validate using the same data as the first example.

Thanks.

**Comment by aldeed** [comment]
Closing old issues. Please comment if this is still an issue and should be reopened.
