### ISSUE TITLE
Collection.attachSchema() turns Collection.update() asynchronous on the server, despite no callback

### ISSUE THREAD

**Issue by nadeemja** [aldeed/meteor-collection2#305]
Hi there,

I have this working code:

```
    // Now repeat for event
    Events.update({
        ext_id: event_in_json.id
    }, {
        $set: {
            ext_id: event_in_json.id,
            client_id: client._id,
            title: event_in_json.title,
            description: event_in_json.description,
            course_id: course_in_db._id
        }
    }, {
        upsert: true,
        validate: false,
        filter: false
    });

    var event_in_db = Events.findOne({
        ext_id: event_in_json.id
    });
```

Again, this code works as it's supposed to.

If I, however, attach any schema to my Events collection, it becomes seemingly asynchronous and **event_in_db** returns **undefined**. It can be any schema, doesn't matter. Even an empty schema breaks the code above code.

For example, even this will break my code: 

```
    Events.attachSchema( new SimpleSchema( {} ) );
```

Does anyone know what's going on? 

Here's a list of packages and their versions in my setup:
http://pastebin.com/raw/32uDTMUR

**Comment by nadeemja** [comment]
Update:

Turns out my ext_id key was set to _String_ in the schema, but I was giving it a Number. 

__Strange__, that I didn't get any error messages to indicate that this was the issue. Even stranger still, ext_id is set to String in other schemas, yet giving those a Number works flawlessly.

**Comment by aldeed** [comment]
Closing old issues. Please comment if this is still an issue and should be reopened.
