### ISSUE TITLE
Collection2/Simple Schema and multiple forms

### ISSUE THREAD

**Issue by seanmiddaugh** [aldeed/meteor-collection2#309]
I have a user profile schema that looks sort of like this:

```
Schema.UserProfile = new SimpleSchema({
    name: {
        type: String,
        optional: false
    },
    gender: {
        type: String,
        optional: false,
        allowedValues: ['Male', 'Female']
    },
    location: {
        type: String,
        optional: false
    },
    age: {
        type: Number,
        optional: false
    }
}
```

My registration form requires the user to select their gender on it. Once registered, the user is presented with another form to fill out the rest of the data: name, location, and age.

Here's the problem: When the user tries to register, I get the error: `Name is required`. The user isn't suppose to enter their name until they register.

What is the proper approach to only validating data that is actually being saved on a specific form?

EDIT

Here is my registration script:

```
var data = {};
var profile = {};
data.email = $('#email').val();
data.password = $('#password').val();
profile.gender = $('#gender').val();
data.profile = profile;

Accounts.createUser(data, function (error) {
   // do
   // ERROR: Name is required
});
```

When the user actually registers, they're presented with a form to fill the other data in. The form submit calls a method that the tries to update the profile object.

**Comment by aldeed** [comment]
Closing old issues. Please comment if this is still an issue and should be reopened.
