### ISSUE TITLE
Relationships

### ISSUE THREAD

**Issue by mquandalle** [aldeed/meteor-collection2#31]
One of the natural evolution of the collection2/simpleSchema/autoForm stack is the ability to define some relationships between models. This feature is build in most popular frameworks (Rails [1], Django [2], Symfony [3]...) and there are no good package for this purpose on Meteor right now. 

I'm sure you already think of this a lot @aldeed. Could you share what are your plans to support relations at the current state?

Some of the questions raised by this topic:
- What relations do we want? For instance rails split the one to many relation into `belongs_to` and `has_one`. Do we need this kind of distinction?
- Do we automatically add fields to collections when we need, or do we let the user define explicitly fields names for relationships with other models?
- How organize the code related to relations, is it more a `collection2` or a `simpleSchema` functionality?
- How do we manage autoForms with relations?
- API to declare a relation? Something like this?

``` js
    Manufacturers = new Meteor.Collection2('manufacturers', { schema: {
        name: {
            type: String
        }
    }});

    Cars = new Meteor.Collection2('manufacturers', {schema: {
        manufacturer: {
            // Associate a relationship type with another model/collection2
            oneToMany: Manufacturers 
        },
        color: {
            allowedValues: ['white', 'black']
        }
    }});
```
- How do we validate a object with relations? Could we add constraints on relations (for instance we might want to limit a blog post to 5 related tags, where posts and tags are both models)?

I think a lot a Meteor users will be interested by this topic, so feel free to post suggestions here :-)

[1] : http://guides.rubyonrails.org/association_basics.html
[2] : https://docs.djangoproject.com/en/1.6/topics/db/models/#relationships
[3] : http://symfony.com/doc/current/book/doctrine.html#entity-relationships-associations

**Comment by chompomonim** [comment]
+1 for this solution and looking for any hacks to do something similar right now.

My problem:
I have list of services in one collection and list of service_providers in other. When adding new service_provider user should be able to select one of available services for services collection. 

Is it possible to do such things right now? Any hacks?

**Comment by benstr** [comment]
@chompomonim this is what I do right now:

**Note:** Below is a simple example. You can expand it with simple-schema arrays/objects and more layers with publish-composite.

1. publish/subscribe a list of **services** to your add **service_providers** route/form.
2. Create a select input with simple-schema to store the relation collection ID:

	```
	serviceId: {
		type: String,
		optional: true,
		regEx: SimpleSchema.RegEx.Id,
		autoform: {
			type: "select",
			options: function() {
				return _.map(Services.find({$or:[{serviceType:"Hospital"},{serviceType:"In-Home"}]}).fetch(), function(service) {
					return {
						label: service.name,
						value: service._id
					};
				});
			}
		}
	},
	```
3. Now that you have the service ID in your service_provider record you can do a lot of things...

	- Use [reywood:publish-composite](https://github.com/englue/meteor-publish-composite) to reactively publish aditional info about the service when you are on the service_provider details page

	 	```
	 	/* PROVIDER DETAIL PAGE */
    Meteor.publishComposite('serviceProviderDetails', function(passedId) {
      if (this.userId) {
        check(passedId, String);
        return {
          find: function(){
            return ServiceProviders.find({_id: passedId}, {});
          },
          children:[
            {
              find: function(providerRef){
                return Services.find({_id: providerRef.serviceId}, {fields:{name: 1}});
              }
            }
          ]
        }
      } else {
        // user not authorized. do not publish secrets
        this.stop();
        return;
      }
    });
	 	```
	- Use [reywood:publish-composite](https://github.com/englue/meteor-publish-composite) to reactively publish a list of providers on the service details page.

		```
		/* SERVICE DETAIL PAGE */
		Meteor.publishComposite('serviceDetails', function(passedId) {
			if (this.userId) {
				check(passedId, String);
				return {
					find: function(){
						return Services.find({_id: passedId}, {});
					},
					children:[
						{
							find: function(serviceRef){
								return ServiceProviders.find({serviceId: serviceRef._id}, {fields:{name: 1, website: 1}});
							}
						}
					]
				}
			} else {
				// user not authorized. do not publish secrets
				this.stop();
				return;
			}
		});
		```
	- Use [tmeasday:publish-counts](https://github.com/percolatestudio/publish-counts/) to reactively publish the total number of providers on a service details page.

		```
		/* SERVICE DETAIL PAGE */
		Meteor.publishComposite('serviceDetails', function(passedId) {
			if (this.userId) {
				check(passedId, String);
				Counts.publish(this, 'providersCounter', ServiceProviders.find({serviceId:passedId}));
				return {
					find: function(){
						return Services.find({_id: passedId}, {});
					}, ...... SEE ABOVE
				}
			}
		});
		```
Hope this helps.

**Comment by aldeed** [comment]
The way @benstr suggested is the way I do it, too. Any eventual relationships development for C2 will be essentially a nice wrapper around that way of doing things.

**Comment by benstr** [comment]
@chompomonim I just remembered another very helpful package for collection manipulation, [matb33:collection-hooks](https://github.com/matb33/meteor-collection-hooks). One my larger projects I use it often, if the circumstances require.

**Comment by chompomonim** [comment]
@benstr thanks for solution and examples. It does work for me well.

**Comment by benstr** [comment]
Nice!

**Comment by meticulo3366** [comment]
Hi, any progress made or examples on how to use relationships? I have used it in Mongoose and SQL databases. Looks like a natural course of development for collection2 and autoform...

**Comment by rdewolff** [comment]
Hi all!
Just went through this long and very interesting topic.
Having relationships implemented would be an amazing plus!
Looking forward to have it!
Cheers!

**Comment by benstr** [comment]
@meticulo3366 & @rdewolff anything implemented would essentially be the same as the [example](https://github.com/aldeed/meteor-collection2/issues/31#issuecomment-68699422) above. **reywood:publish-composite ** (and a few others like it) have become somewhat of the standard from what I have seen. @aldeed has done a great job supporting his packages, the effort has to be fairly large and time consuming... Just saying, it probably best for us all to get acquainted with **reywood:publish-composite **, instead of waiting for collection2. Especially with all the DB changes coming to Meteor soon.

**Comment by metalik** [comment]
thanks @benstr you saved my day~~!!!

**Comment by benstr** [comment]
@metalik :+1:

**Comment by AlexFrazer** [comment]
+1, very support. For an "initial draft", I think it could be cool to just make it short hand

```
classes: {
  type: ForeignKey(Classes),
  autoform: {
    foreignKeyLabel: 'name'
  }
}
```

which could basically just be

```
classes: {
  type: String,
  allowedValues: function() {
    return Classes.find().map(doc) {
      return doc._id;
    }
  },
  autoform: {
    options: function() {
      return Classes.find().map(doc) {
        return { label: doc.name, value: doc._id }
      }
    }
  }
}
```

**Comment by dandv** [comment]
Looks like @jagi's [Astronomy already implements relationships](https://github.com/jagi/meteor-astronomy/wiki/Relations).

**Comment by lukemt** [comment]
> DB changes coming to Meteor soon. 

@benstr 
Let me know a little bit more this.

**Comment by brylie** [comment]
The Astronomy [relationship syntax](https://github.com/jagi/meteor-astronomy/wiki/Relations#adding-relations) seems pretty simple.

```js
relations: {
    addresses: {
      type: 'many',
      class: 'Address',
      local: '_id',
      foreign: 'memberId'
    }
}
```

**Comment by petermikitsh** [comment]
I think a sugared syntax (essentially what @AlexFrazer suggested) would be awesome.

**Comment by omeid** [comment]
Having this feature would be awesome and the planning seems to be going great.

However, for the time being, what is the "right" way to handle this? How do you guys go about it? I would appreciate some sort of guide or write up on this topic.

**Comment by omeid** [comment]
And +1 for the @AlexFrazer suggestion. It is a very "natural" way to go and can be improved behind the scene overtime.

**Comment by carlosbaraza** [comment]
Any news on this? I would appreciate to receive some guidance about how to achieve something similar without this feature, like @omeid suggested.

**Comment by brylie** [comment]
@carlosbaraza check out the [collection helpers]() package. It can be used to design methods to retrieve related documents, such as those linked by a `remoteDocumentId` field. E.g. you can store the remote document ID in a `remoteDocumentId` field and write a `remoteDocument` helper to traverse the collection based on the `remoteDocumentId` field.

**Comment by carlosbaraza** [comment]
Hi @brylie,

Thank you for your answer. It is a very interesting package.

**Comment by keyscores** [comment]
@aldeed Haven't seen your comment here in a while. Can you update us on your thoughts for this. Thanks in advance, and keep up the good work.

**Comment by micouz** [comment]
**For newcomers mostly**

After reading this long thread and trying it out for myself, I settled on using both [reywood:publish-composite](https://github.com/englue/meteor-publish-composite) and [dburles:collection-helpers](https://github.com/dburles/meteor-collection-helpers).

For example, imagine you have a list of tasks, and you want to display their text AND their owner's name, stored in another document. Also, you want your client to update whenever an owner's name changes. In other words, you want an "atomic" publication consisting of both the task and its owner. This is where publish-composite comes into play :

```javascript
Meteor.publishComposite('tasks', {    
    find: function () { // Return a cursor for the list of tasks
        return Tasks.find();
    },
    children: [
        {
            find: function (task) { // Return a cursor for the owner of each specific task
                return Meteor.users.find(task.ownerId, {fields: {username: 1}});
            }
        }
    ]
});
```

So now, we have all the data published to the client. And every time an owner name changes, any piece of UI watching for changes to the list of tasks will be reactively updated !

Now, to conveniently get the owner from a specific task, we use use collection-helpers :

```javascript
Tasks = new Mongo.Collection('tasks');
Tasks.helpers({
    findOwner() {
        return Meteor.users.findOne(this.ownerId)
    }
});
```

Finally, just get the owner's name :

```javascript
Tasks.findOne().findOwner().username
```

If you want to see it in action, checkout [this small project](https://github.com/micouz/meteor-react-tutorial-next)

**Comment by carlosbaraza** [comment]
Hi @micouz,

Thank you for the explanation, that is quite useful. I was also using dburles:collection-helpers, keeping the id/ids of the nested collection objects in the main collection objects.

Cheers,
Carlos..

**Comment by benstr** [comment]
Nice @micouz ! It would be useful on long issues like this one for GitHub to allow for sticky comments.

**Comment by SeanOceanHu** [comment]
awesome :100:

**Comment by takahser** [comment]
I have an issue on the example in the RELATIONSHIP.md file [1]

I wanted to test the Cars example, so I added all of the collections to my meteor application, but now it would crash when running, cuz Cars is accessed in Colors before declared:


    ReferenceError: Cars is not defined
      at app/collections/cars.js:15:14
      at app/collections/cars.js:45:3
      at /Users/XXX/.meteor/local/build/programs/server/boot.js:222:10
      at Array.forEach (native)
      at Function._.each._.forEach (/Users/XXX/.meteor/packages/meteor-tool/.1.1.3.ik16id++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
      at /Users/XXX/.meteor/local/build/programs/server/boot.js:117:5

    Exited with code: 8
    Your application is crashing. Waiting for file change.  

[1] https://github.com/aldeed/meteor-collection2/blob/master/RELATIONSHIPS.md

**Comment by luixal** [comment]
Yep, an update on this would be great! :)

**Comment by kanekotic** [comment]
@takahser I think that what is on Relationship.md is just a vision and it doesn't reflect the current implementation on his 100%. But i agree that displaying a dropdown in quickform when referencing another will be a really powerful thing.

I agree also with what is defined in the .md file it should be a reference to the collection and not to the  schema. Should look like this:
```javascript
ThisCollection = new Mongo.Collection('thisCollection');
OtherCollection = new Mongo.Collection('otherCollection');

OtherCollectionSchema = new SimpleSchema({ // object type schema
    name: {
      type: String
    }
});

ThisCollectionSchema = new SimpleSchema({
    type: {
        type: OtherCollection,
        optional: true
    },
    title: {
        type: String
    }
});

OtherCollection.attachSchema(OtherCollectionShema);
ThisCollectionSchema.attachSchema(ThisCollectionSchema);
```

**Comment by luixal** [comment]
@kanekotic @takahser that's what I'm doing right now using one of the selectize autoform packages around.

Also selectize allow you to easily make that selector multiple (really powerful when you have a document related to several docs in other collection stored as an array of IDs) :)

**Comment by Mapuia** [comment]
Do we have any update on relationships like one-to-many, many-to-many etc. defining with has_one, has_many, belongs_to etc..

**Comment by oohaysmlm** [comment]
I was also having trouble with this issue, and needed a quick and easy way to add a reference (or references) to documents in another collection.  I quickly put together a package called "autoform-relations" to help with this.  It uses meteorhacks:searchsource to provide a reactive search against specified fields in the other collection and allows you to add or remove the desired documents.  What actually get's stored is an [String] of document ids.

I put it together quickly but if people find it useful I'm happy to add more to is [https://github.com/oohaysmlm/autoform-relations](https://github.com/oohaysmlm/autoform-relations)

I use publish-composite  to create publications after I've linked the documents up with this custom autoform input.

**Comment by thebarty** [comment]
Hi guys,

I think those relations should be defined in SimpleSchema/Collection2. 

I have spend some time on a write-up for a feature to denormalize those relations and put it into a readme. This is a proposal and no finished package... it might serve as an inspiration though https://github.com/thebarty/meteor-denormalization

**Comment by Lukasvo** [comment]
You're going to want to check out [Grapher](http://grapher.cultofcoders.com/index.html)
