### ISSUE TITLE
Merged multiple Schemas are not updated on the client Collection

### ISSUE THREAD

**Issue by artjomg** [aldeed/meteor-collection2#311]
Hi, 

I am using the multiple Schemas merge within a server method call, which works fine.
But how to make sure that the client Collection is also updated with the new attributes?
Autoroform and tabular table are not updated with the new information. It it is not reactive is there a way to re-trigger the Collection init on the client side?

Thnx.
Artjomg

**Comment by aldeed** [comment]
Closing old issues. Please comment if this is still an issue and should be reopened.
