### ISSUE TITLE
collection-helpers and upserts aren't cleaned correctly

### ISSUE THREAD

**Issue by dandyrandy** [aldeed/meteor-collection2#317]
When using collection-helpers and defining helper methods, I can insert() and update() the documents as expected. However, if I try to upsert(), or pass {upsert: true} to update(), the attributes introduced by collection-helpers get rejected as being disallowed by schema. It appears they aren't being filtered out.

**Comment by aldeed** [comment]
Closing old issues. Please comment if this is still an issue and should be reopened.
