### ISSUE TITLE
Uncaught Error: After filtering out keys not in the schema, your object is now empty

### ISSUE THREAD

**Issue by samvv** [aldeed/meteor-collection2#319]
This error occurs when an empty serialized data object (with keys set to the empty string) is passed to `People.insert`. If I understand correctly, this is wrong, and should instead emit an error telling that the field `fullname` and `email` are required.

```
People = new Mongo.Collection("people")

Schema.People = new SimpleSchema({
  fullname: {
    type: String
  },
  alias: {
    type: String
    optional: true
  },
  email: {
    type: String
    max: 254
    regEx: SimpleSchema.RegEx.Email
  },
  gender: {
    type: String
  },
  phone: {
    optional: true,
    type: String
  }
})

People.attachSchema(Schema.People)

People.insert({fullname: "", alias: "", email: "", password: "", repassword: ""})
```

**Comment by lawrentiy** [comment]
I agree with it. 
Such behavior breaks all my logic. And that error doesn`t  catched in Collection.insert callback as error argument.

**Comment by kctang** [comment]
Did you try calling [clean()](https://github.com/aldeed/meteor-simple-schema#cleaning-data) on the client before insert/update actions?

I think it has something to do with "The Collection2 package always calls clean before every insert, update, or upsert." mentioned in that page.

**Comment by rikyperdana** [comment]
`Exception in setInterval callback: Error: After filtering out keys not in the schema, your modifier is now empty`
I don't have any ideas what to do with it

**Comment by meteorplus** [comment]
@rikyperdana just cry and it will work! since this is a dumb error wtf do you expect us to do here @aldeed ?? thanks for all your work but this is so weird!!

**Comment by JulianKingman** [comment]
Anyone having any luck?

**Comment by JulianKingman** [comment]
Two hours later... Just had to put `blackbox: true` on my objects (objects I don't care to validate).

**Comment by Anoop-Goudar** [comment]
Hi, I was facing the similar issue.
I added schema directly to the collection as shown below, without using the attachSchema() method and it worked for me.

People.attachSchema(Schema.People) // remove this line and replace with below line.

People.schema = Schema.People;

hope it solves the issue.
Happy Coding!

**Comment by SaydChada** [comment]
Hi, the error may occur if you attempt to save empty data (obviously if you try to save field that is not in schema's definition, error will be thrown), please at least in error's message tell us the field's name which fired the error

**Comment by alejandroiglesias** [comment]
Knowing the offending field or schema, as @SaydChada suggests, would be so much useful. I cannot find why I'm seeing this error.

**Comment by arshs** [comment]
in case this helps - anyone - make sure you haven't accidentally attached your schema before defining it :)

MyCollection.attachSchema(MyCollection.schema); 

must come after the

MyCollection.schema = new SimpleSchema({ ..... otherwise it will obviously be a blank schema.

**Comment by Mklueh** [comment]
In my case I was trying to update a field with the wrong datatype (String with undefined)

**Comment by eminx** [comment]
I don't know which one of these, but this implementation fixed my problem:
```
    roles: {
        type: Object,
        optional: true,
        blackbox: true
    },
    heartbeat: {
        type: Date,
        optional: true
    }
```

It was suggested here: https://github.com/aldeed/meteor-collection2#attach-a-schema-to-meteorusers

**Comment by JSmith2412** [comment]
In my case it was because the schema wasn't available in the context, I had imported incorrectly. Rookie mistake but just so ya' know it can also cause this kind of exception.

**Comment by usermadhan** [comment]
Anoop-Goudar's suggestion works for me... not sure what it is

**Comment by aldeed** [comment]
This is because by default SimpleSchema cleaning does `removeEmptyStrings` and then `filter`. So the props with string values become undefined, and then are removed because they are undefined. This is the default because it helps keep the database smaller (unlike SQL, in mongo null/empty props do take up space).

If it happens that `filter` ends up removing all of the props, then you get this error.

Cleaning defaults can be changed per schema: https://github.com/aldeed/simple-schema-js#set-default-cleaning-options

Or per operation: https://github.com/aldeed/meteor-collection2#inserting-or-updating-without-cleaning

**Comment by shivangsaratasort** [comment]
> Hi, I was facing the similar issue.
> I added schema directly to the collection as shown below, without using the attachSchema() method and it worked for me.
> 
> People.attachSchema(Schema.People) // remove this line and replace with below line.
> 
> People.schema = Schema.People;
> 
> hope it solves the issue.
> Happy Coding!

This solution worked for me.
