### ISSUE TITLE
New Package "Schematempaltes" for collection2

### ISSUE THREAD

**Issue by Pushplaybang** [aldeed/meteor-collection2#321]
This provides prebuilt re-usable autovalue schema templates to be used with the meteor aldeed:collection2 package.

Automatically, and very quickly, include useful values in your collection schema such as the following :
- CreatdAt date
- UpdatedAt date
- CreatedBy userId
- UpdatedBy userId
- history

its available on atmosphere here https://atmospherejs.com/pushplaybang/schematemplates
Or find it on Github : https://github.com/Pushplaybang/Meteor-schema-templates

Would you be willing to add it to README?

**Comment by aldeed** [comment]
Never looked at this. I'd accept a PR to add to readme, but now that SimpleSchema is an NPM package, it would be better if this package were also moved to NPM so it can work for people not using Meteor, too.

**Comment by Pushplaybang** [comment]
@aldeed  - that's alright, its out of date now, I'd like to do a v2 and release it on npm.  Once I get around to that, I'll open PR appropriately.
