### ISSUE TITLE
validation reports date error only on Safari

### ISSUE THREAD

**Issue by dpatte** [aldeed/meteor-collection2#322]
I am validating a date field, and I am replacing the field by a string. This works fine in FF & Chrome, but with Safari, validation reports 'field must be a date'. If I bypass validation on Safari, the record get saved correctly.
I traced down into your code and noticed that you have a special condition coded for Safari, and this patch seems to trigger the validation error report.

**Comment by aldeed** [comment]
Closing old issues. Please comment if this is still an issue and should be reopened.
