### ISSUE TITLE
How to import SimpleSchema from aldeed:collection2 in Meteor with ES6

### ISSUE THREAD

**Issue by aligos** [aldeed/meteor-collection2#323]

**Comment by neutrous** [comment]
Have a try with:
```javascript
   import { SimpleSchema } from 'meteor/aldeed:simple-schema';
```

**Comment by joshua1** [comment]
While that works, you get ```undefined is not a function``` cos of the data types (String, Number, Boolean) etc

**Comment by jalalat** [comment]
declare the variables in any typings file like this:

declare let SimpleSchema: any;
declare let ValidatedMethod: any;
declare let DDPRateLimiter: any;
declare let _: any;

**Comment by bastiW** [comment]
On Collection 2 2.x.x it is 

`import SimpleSchema from 'simpl-schema';`

Like it is written here:
https://github.com/aldeed/meteor-collection2/#important-note-the-version-in-this-repo-is-deprecated
