### ISSUE TITLE
Dynamic Array

### ISSUE THREAD

**Issue by AlexCatch** [aldeed/meteor-collection2#327]
I'm having issues defining a schema for my collection.

The issue is that in the collection I store an array of dynamic objects that represent a form.
The value in the objects can be whatever, validating the contents of the object does not matter, just making sure that 'form' key in the schema is an array of type 'Object'.

When I set the type of 'forms' to [Object], the documents get rejected when inserting an object.

Any idea how to get around this?

**Comment by rafaelrpinto** [comment]
Define your schema with:
```javascript
"forms.$": Object,
    "forms.$.formName": String,
    "forms.$.formValue": {
        type: Object,
        blackbox: true
    }
```

the form name will be validated just like the other fields, but formValue will not because of blackbox=true

**Comment by aldeed** [comment]
Closing old issues. (The answer is to make the objects `blackbox: true`)
