### ISSUE TITLE
validate documents with embedded document

### ISSUE THREAD

**Issue by siminchengithub** [aldeed/meteor-collection2#333]
Does the simpleSchema work for embedded document? See example below.
coachSchema = new SimpleSchema([baseUserSchema,{
    teamID : {type:String},
    notes:{type:[{
        itemID:{type:String},
        text:{type:String}
    }]}
}])

**Comment by jpmoyn** [comment]
@siminchengithub For future reference, when you want to put code into an issue or a comment on GitHub, you should make it into a code snippet for more legibility. 

I am a bit confused about what you mean when you say embedded document, but I am assuming you mean nested arrays or objects on the user object? Below I have a small sample profile schema for users that uses both nested objects and an array. 

```
Meteor.users.schema = new SimpleSchema({
  _id: {
    type: String,
    regEx: SimpleSchema.RegEx.Id
  },
  username: {
    type: String,
    trim: true,
    regEx: SimpleSchema.RegEx.Email
  },
  'emails.$.address': {  // this is where the email array comes into play, when you nest objects or arrays, put the key in quotes
    type: String,
    trim: true,
    regEx: SimpleSchema.RegEx.Email
  },
  'emails.$.verified': {
    type: Boolean
  },
  'profile.phone': {   // now here is the profile object within the user object, again you use quotes, but you don't need to use a "$" because it is not an array
    type: String,
    min: 10,
    max: 10,
    trim: true
  },
  'profile.fn': {
    type: String,
    trim: true
  },
  'profile.email': {
    type: String,
    trim: true,
    regEx: SimpleSchema.RegEx.Email
  }
});
```


If I am correct in assuming you meant a nested array or object when you say embedded document, this information is all explained in the docs. Next time be sure to read through them before submitting an issue to the repo.

**Comment by DerekTBrown** [comment]
I am not sure if this is what @siminchengithub is describing- but it would be cool to have a shortcut to verify that a given field is a valid id in another collection.  For example, if I had a collection "sports" and a collection "teams", and each team contained a "sport_id" string, it would be cool if there was an easy way to validate that the "sport_id" is indeed the id of an object in the "sports" collection.

**Comment by jpmoyn** [comment]
@DerekTBrown If I am not mistaken, this is easily achievable with the custom validation provided with the package.

**Comment by DerekTBrown** [comment]
I understand it is possible- indeed, it is something I have already implemented.  It just seems like a common usecase to the point that it may be worth working into the package directly.

**Comment by aldeed** [comment]
Closing old issues. Please comment if this is still an issue and should be reopened.
