### ISSUE TITLE
getAutoValues in find()

### ISSUE THREAD

**Issue by surajiyer** [aldeed/meteor-collection2#334]
Is it possible to perform recalculate autoValues on performing a find() operation. An example scenario where this would help is,

```
deadline: {
    type: Date,
    custom: function () {
        // if deadline is before current time, give Invalid deadline error
        if (this.value < new Date) return "invalidDeadline";
    }
},
ended: {
    type: Boolean,
    optional: true,
    autoValue: function () {
        return new Date > this.siblingField('deadline').value;
    }
}
```

Rerunning the autoValue function of the ended field upon doing a find() operation will result in the ended value being updated based on the current time. I am thinking something along the lines of find({}, {getAutoValues: true}) same as in Collection2 for the insert operation.

**Comment by jpmoyn** [comment]
Have you considered using a Cron job to update your documents that have gone past their deadline? If I understand your dilemma, Cron seems like the perfect tool for it.

You could have it run at any time interval you like, and it is an extremely versatile tool.

I use Cron all of the time for updates similar to this one.

**Comment by surajiyer96** [comment]
I did think of using the cron package but felt it is less overhead to only update with autoValues on find(). This way there is no need for unnecessary updating of the values.

**Comment by aldeed** [comment]
Closing old issues. Please comment if this is still an issue and should be reopened.
