### ISSUE TITLE
Make collection2 play nicer with modularized style

### ISSUE THREAD

**Issue by ndarilek** [aldeed/meteor-collection2#335]
I'm currently encountering vsivsi/meteor-file-collection#125. I don't know specifically what is causing it, but the console logs make it look like there's some clash between FileCollection and the collection2 prototype.

I'd like to use collection2, but not automatically and not everywhere. Any chance we might get a way to:

```
import {Collection2} from "meteor/aldeed:collection2"
const Documents = new Collection2(...)
```

It doesn't currently appear possible to opt out of the monkeypatch, but this may be causing issues for other packages. I have to import mongo now anyway, so why not let me selectively opt into collection2 use when I want it?

Thanks.

**Comment by aldeed** [comment]
Closing old issues. Please comment if this is still an issue and should be reopened.
