### ISSUE TITLE
custom validator function does not run for updates on object fields

### ISSUE THREAD

**Issue by gferreri** [aldeed/meteor-collection2#337]
I have a scenario where certain fields are required only when another property is true. Following the example [here](https://github.com/aldeed/meteor-simple-schema#make-a-field-conditionally-required) but modifying the `type` field to _MyOtherSchema_, the custom function only runs on _insert_ and not _update_ or _upsert_. However, the custom function _does_ run on updates if the type is String. Is this expected behavior? How can I get the custom function to run for updating objects?

```
{
  field: {
    type: MyOtherSchema,  //<----- different from example, not a simple value type
    optional: true,
    custom: function () {
      var shouldBeRequired = this.field('saleType').value == 1;

      if (shouldBeRequired) {
        // inserts
        if (!this.operator) {
          if (!this.isSet || this.value === null || this.value === "") return "required";
        }

        // updates
        else if (this.isSet) {
          if (this.operator === "$set" && this.value === null || this.value === "") return "required";
          if (this.operator === "$unset") return "required";
          if (this.operator === "$rename") return "required";
        }
      }
    }
  }
}
```

Note that if type is Object instead of MyOtherSchema, the behavior is the same, i.e. custom validator is not executed.

**Comment by aldeed** [comment]
Closing old issues. Please comment if this is still an issue and should be reopened.
