### ISSUE TITLE
omitted field of sub-schema in an array is cleared (set to undefined) when update

### ISSUE THREAD

**Issue by xgfd** [aldeed/meteor-collection2#339]
```
let sub = new SimpleSchema({
    name: {
         type: String,
    },
    autoform: {omit: true}
});

let main = new SimpleSchema({
    arrOfSub: {type: [sub]}
});
```

In the above example `name` in the sub-schema was always set to `undefined` when updating a sub document (even if add an `autoValue` field that calls `this.unset()` in `sub.name`). My guess was that updating a sub document causes `main.arrOfSub` to be updated, and that in turn adds a `$set` modifier to all fields of the updating sub (probably all subs in the array). Since an omitted field has `undefined` as its value, those fields are cleared.

Actually putting `autoValue`  to `main.arrOfSub`   that calls `this.unset()` at update fixed the issue (shown below). But to me it's a confusing behaviour (probably due to my lack of understanding of how this package works on sub docs in an array).

```
let main = new SimpleSchema({
    arrOfSub: {
        type: [sub], 
        autoValue(){
            if(this.isUpdate) {
                this.unset();
            }
        }
    }
});
```

Would it be helpful to provide more examples with nested sub-schemas  under `autoValue` in the documentation to clarify cases like the one above?

**Comment by aldeed** [comment]
Closing old issues. Please comment if this is still an issue and should be reopened.
