### ISSUE TITLE
Error with Meteor 1.4

### ISSUE THREAD

**Issue by nicooprat** [aldeed/meteor-collection2#341]
Just tried to upgrade to Meteor 1.4.0.1, and I got this kind of errors: "0 must be a string". For example, my field schema is defined like this:

``` js
stories: {
  type: [String],
  defaultValue: [],
  optional: true
}
```

And I'm updating it like this:

``` js
Users.update(userId, {
  $push: {
    stories: doc._id
  }
});
```

Debugger; tells me that `doc._id` is correctly defined. Am I doing anything wrong?

Downgraded to 1.3.5.1, working fine again. May be related to the Mongo 3.x update?

**Comment by serkandurusoy** [comment]
Did you try type casting that `0` to string with `toString()` or `''+doc._id` as a workaround to whatever may be causing that issue? And is `doc._id` maybe actually `=== 0` ?

**Comment by aldeed** [comment]
Closing old issues. Please comment if this is still an issue and should be reopened.
