### ISSUE TITLE
Required fields in an object field throwing errors when updating

### ISSUE THREAD

**Issue by MechJosh0** [aldeed/meteor-collection2#342]
When submitting a field update for an existing document the document will update perfectly fine, this is the expected behaviour. However, when submitting an update for a field inside an object it'll throw an error saying the other fields in this object are required even though they already exist in the document, this is not the expected behaviour.

For example, this is my schema:
```
const schema = {
  item: {
    type: Object,
    optional: true
  },
  'item.name': {
    type: String,
    min: 5,
    max: 10,
    label: 'Item name'
  },
  'item.quantity': {
    type: String,
    label: 'Item quantity'
  },
  name: {
    type: String,
    label: 'Name'
  },
  another: {
    type: String,
    label: 'Another'
  },
  age: {
    type: Number,
    min: 0,
    max: 20,
    optional: true,
    label: 'Age'
  }
};
```

And this is my document that I'm trying to update:
```
{
  "id": "4ccaf912-47ca-4fef-acbd-334efc90da98",
  "age": 6,
  "item": {
    "name": "My item name 1",
    "quantity": "21"
  },
  "name": "Hello name 1",
  "another": "Another 1"
}
```

I use the following object to update to my document:
```
{
  "name": "Hello name 2"
}
```
This will update my document, as expected. The required fields which already exist in the document (ie `another`) do not cause an error as they exist in the document so they do not need to be passed through again as there are no changes.

Now, if I pass the following object to my document:
```
{
  "item": {
    "name": "My item name 2"
  }
}
```
This will throw the error `Item quantity is required`, this is not expected. The value already exists in the document so it shouldn't be passed through again.

Unless I'm doing something wrong, I believe this is a bug. If this is an error on my side, please point me in the right direction.

In the mean time, I'm solving this problem by passing through the entire document (with updated values) which is unnecessary data being sent around.

**Comment by MechJosh0** [comment]
Nevermind, I see this is a [known issue](https://github.com/aldeed/meteor-collection2#subobjects-and-arrays-of-objects).

**Comment by SimonVuong** [comment]
@MechJosh0 

i understand why

```
{
  "item": {
    "name": "My item name 2"
  }
}
```

succeeds but why does 

```
{
  "name": "Hello name 2"
}
```

succeed? shouldn't it say `Another is required`??
