### ISSUE TITLE
defining an array in simple scheme

### ISSUE THREAD

**Issue by maitahlcor** [aldeed/meteor-collection2#343]
hi, Im trying to define an array in simple schema, so I'm wondering if there is an special way to define arrays in Simple Schema, because I have tried several ways and always geting errors

emails: {
       type: Array,
   },
   "emails.$": {
       type: Object
   },
   "emails.$.address": {
       type: String,
       autoValue: function() {
           return Meteor.uuid();
       },
       regEx: SimpleSchema.RegEx.Email
   },
   "emails.$.verified": {
     type: String,
     autoValue: function() {
         return Meteor.uuid();
   },

but meteor is returning this  error
W20160804-00:58:33.026(-5)? (STDERR) Error: Emails is required
W20160804-00:58:33.028(-5)? (STDERR)     at getErrorObject (packages/aldeed_collection2-core/lib/collection2.js:437:1)
W20160804-00:58:33.029(-5)? (STDERR)     at [object Object].doValidate (packages/aldeed_collection2-core/lib/collection2.js:420:1)
W20160804-00:58:33.033(-5)? (STDERR)     at [object Object].Mongo.Collection.(anonymous function) [as insert](packages/aldeed_collection2-core/lib/collection2.js:173:1)
W20160804-00:58:33.038(-5)? (STDERR)     at server/stratup.js:20:20
W20160804-00:58:33.042(-5)? (STDERR)     at C:\Users\def1\probar\sprint_1.meteor\local\build\programs\server\boot.js:304:5

only if I use the  optional true, meteor didn't show the error but mongo neither return the array

**Comment by aldeed** [comment]
Closing old issues. Please comment if this is still an issue and should be reopened.
