### ISSUE TITLE
Upsert validation with DenyUpdate

### ISSUE THREAD

**Issue by pcmaffey** [aldeed/meteor-collection2#346]
When using Upsert to insert a new record into collection with schema set to { DenyUpdate: true }, getting error message: Error: [fieldName] cannot be set during an update(…). Seems like its denyingUpdate for all upsert calls.

Not a huge issue, can use insert & update instead... Just fyi.

**Comment by aldeed** [comment]
Closing old issues. Please comment if this is still an issue and should be reopened.
