### ISSUE TITLE
how to remove Invalid keys (  [field] is not allowed by schema)

### ISSUE THREAD

**Issue by devarashetty** [aldeed/meteor-collection2#347]
I am using SimpleSchema to a collection .One of the doc has a value which is not mentioned in schema and when I am trying to update the issue I am getting error `[field] is not allowed by schema`

**Comment by devarashetty** [comment]
@aldeed  please let me know your suggestion on this issue

**Comment by aldeed** [comment]
Closing old issues. Please comment if this is still an issue and should be reopened.
