### ISSUE TITLE
namespace conflict when using simpl-schema (npm, 2.x)

### ISSUE THREAD

**Issue by hyperborea** [aldeed/meteor-collection2#348]
I'm using the aldeed:collection2 package and have recently switched to the simpl-schema (2.0) npm module. Sadly as collection2 also implies aldeed:simple-schema (1.x) that causes a namespace conflict resulting in meteor-schema-index to extend the wrong library.

For now I'm duplicating the following code, but is there a better way?

```
import SimpleSchema from 'simpl-schema';

SimpleSchema.extendOptions({
  index: Match.Optional(Match.OneOf(Number, String, Boolean)),
  unique: Match.Optional(Boolean),
  sparse: Match.Optional(Boolean),
});
```

**Comment by hyperborea** [comment]
In fact the namespace issue is already problematic for collection2 itself as it invokes the wrong library. Am I using it wrong?

**Comment by yanickrochon** [comment]
This package should drop it's dependency to simpl-schema and tell the user to import their own. I am having problem using SimpleSchema as this package imports a version that is not compatible with the npm implementation (e.g. error when using `SimpleSchema.oneOf`, no support for `foo.$.bar`, etc.)

Make this package use the correct simpl-schema package, or make users import it from npm directly. In any case, this will make maintenance easier for everyone.

See [this related issue](https://github.com/aldeed/meteor-simple-schema/issues/663).

**Comment by Gervwyk** [comment]
Any updates on this issue? What is the possibility for a npm collection2 module?

**Comment by ramijarrar** [comment]
@Gervwyk there was some more recent activity [here](https://github.com/aldeed/node-simple-schema/issues/8)

**Comment by aldeed** [comment]
Closing old issues. Please comment if this is still an issue and should be reopened.
