### ISSUE TITLE
can not disable trim

### ISSUE THREAD

**Issue by elisei-timofte** [aldeed/meteor-collection2#350]
I need to save spaces in the DB but the `trim: false` option does not work.

**Comment by elisei-timofte** [comment]
Any updates on this issue?. Right now I had to remove the whole schema from that collection so I can make it run. It would be nice if we can fix this. Thanks!

**Comment by cyllu2** [comment]
I have the same error. Wonder what kind of moron made this package.

**Comment by elisei-timofte** [comment]
I've found an workaround: `YourCollection.insert data, {trimStrings: false}`
