### ISSUE TITLE
Issue in inserting two different schemas into the same collection

### ISSUE THREAD

**Issue by psaelango** [aldeed/meteor-collection2#352]
@aldeed 
I'm trying to insert two different schemas into a single collection. Just for example

**Collections.js Code**

``` javascript
Employee = new SimpleSchema ({
        EmpNo: {
          type: Number,
          label: "EmpNo"
        },
        EmpAddress: {
          type: String,
          label: "EmpAddress"
       }
});
Student = new SimpleSchema ({
        StuNo: {
          type: Number,
          label: "StuNo"
        },
        StuAddress: {
          type: String,
          label: "StuAddress"
       }
});
SampleCollection.attachSchema(Employee);//attempt[1]
SampleCollection.attachSchema(Student);//attempt[1]
/*Also I've tried*/
doc=this._id;
SampleCollection.attachSchema(Employee, doc, {selector: {type: 'a'}});//attempt[2]
SampleCollection.attachSchema(Student, doc, {selector: {type: 'b'}});//attempt[2]
```

**`Similarly in Client code`** 

``` javscript
attempt[1]
{{> quickForm collection="SampleCollection" schema="Employee" id="insertEmployeeForm" type="insert"}} 
{{> quickForm collection="SampleCollection" schema="Student" id="insertStudentForm" type="insert" }}
attempt[2]
 {{> quickForm collection="SampleCollection" schema="Employee" id="insertEmployeeForm" type="insert"  doc=this selector="type:'a'"}}
{{> quickForm collection="SampleCollection" schema="Student" id="insertStudentForm" type="insert" doc=this selector="type:'b'"}}
```

Either way I'm getting error
Error for attempt[1] - collection.SimpleSchema() requires doc argument
Error for attempt[2] -  Error - Require StuNo || EmpNo (other schema attribute) 

When i googled, I came across similar errors - https://github.com/aldeed/meteor-collection2-core/issues/6. 

So is the issue still open?

**Comment by sosoviak** [comment]
+1

**Comment by sosoviak** [comment]
@psaelango I don't use autoform. I use Collection2 with React but i solve this error by adding form data in collection.simpleSchema call:
`collectionName.simpleSchema(data).namedContext()`

**Comment by psaelango** [comment]
@sosoviak - But can you mention which schema to attach to the collection. Is (data) - your form data? Can you please provide a sample code (or) example

**Comment by sosoviak** [comment]
@psaelango when you have more than one schema in a collection it fails if you make any calls to `db.simpleShema()` without pass your data as parameter. 

Server:
```
Meteor.methods({
	'ingresos.insert'(data) {
		check(data, Object);
		db.insert(data);
	}
});
```
Client:
```
_submitHandle(object, e) {
    e.preventDefault();
    Meteor.call('ingresos.insert', data, this._onSubmitCallback.bind(this, data));
}
_onSubmitCallback(data, error, result) {
		if (error) {
                        let valContext = db.simpleSchema(data).namedContext(),
                              invalidKeys = valContext.invalidKeys(),
                              errors = [];
	                _.each(invalidKeys, (key) => {
		            errors.push(valContext.keyErrorMessage(key.name));
	                 });
			this.setState({formErrors: errors});
		} else {
                    //ok
		}
}
```

**Comment by aldeed** [comment]
Closing old issues. Please comment if this is still an issue and should be reopened.

**Comment by nosizejosh** [comment]
I have just refactored my collection into separate schema after reading the readme section about attaching multiple schemas, only to get stuck with the `Error: collection.simpleSchema() requires doc argument when there are multiple schemas`
I have researched quite a bit to find a solution but nothing has worked. 
https://github.com/aldeed/meteor-collection2-core/issues/6
https://github.com/aldeed/meteor-autoform/issues/1506.


I am using blaze and autorform hooks , with the relevant section of my code below;
//hook
```
AutoForm.hooks({
  addOrganizationForm:{
      onSubmit: function (insertDoc, updateDoc, currentDoc) {
        this.event.preventDefault();
        var self = this;
        let insertOrdersArgs = {
          orderType: 'registerOrganization',
          orderDetails: insertDoc      
        };
```

// form
`  {{ #autoForm collection=AutoFormCollections.Organizations id="addOrganizationForm" schema=AutoFormCollections.licensorSchema}}
`
// template code
because i am using autofrm hooks, i have nothing in the events code for this form

how do I  resolve the error please
