### ISSUE TITLE
Inserting a nested object clears said Object in place

### ISSUE THREAD

**Issue by bkuster** [aldeed/meteor-collection2#354]
I have a schema attached to a collection, as follows:

``` javascript
const schema = new SimpleSchema({
  name: { type: String },
  nested: { type: Object },
  list: { type: [String] }
});
const Items = new Mongo.Collection('items');
Items.attachSchema(schema);
```

Using a method, I insert a new document: 

``` javascript
function insertNewDoc({ name, nested, list }) {
  // some things with list
  Items.insert({ name, nested, list });
}

const newDoc = {
  name: 'name',
  nested: { 
    one: 1
  },
  list: ['one','two']
};
insertNewDoc(newDoc)

console.log(newDoc) // prints { name: name, nested: {}, list: ['one','two'] }
```

Thus if I wish to use the **nested** Object later on, I need to _clone_ the `nested` parameter of my `insertNewDoc`Function before passing it to insert.

**Update**
Adding the information of the nested object to the schema, solves the problem.

**Comment by aldeed** [comment]
Closing old issues. Please comment if this is still an issue and should be reopened.
