### ISSUE TITLE
Insert valid url on empty string

### ISSUE THREAD

**Issue by Deelux** [aldeed/meteor-collection2#357]
Hi there, 

For some reason my values are not getting "clean'ed". In my schema I have:
`  videoLink: {
    type: String,
    regEx: SimpleSchema.RegEx.Url,
    label: 'The url of the file.',
    optional: true},
`

But when I insert it into the collection I still get a insert valid url error. 

How can I fix this?

**Comment by aldeed** [comment]
Closing old issues. Please comment if this is still an issue and should be reopened.
