### ISSUE TITLE
Pushing to an array on upsert() not supported? 

### ISSUE THREAD

**Issue by derwaldgeist** [aldeed/meteor-collection2#375]
I have the following schema:

```js
export const checkinSchema = new SimpleSchema({
  // location id
  locationId: {
    type: String,
    index: 1
  },
  // checkins users make at a location
  checkins: {
    type: [Object]
  },
  // user checking in
  'checkins.$.userId': {
    type: String,
    index: 1
  },
  // time-stamp
  'checkins.$.time': {
    type: Date
  }
});
```

and the following upsert code:

```js
checkinsCollection.upsert(
  { locationId },
  { $push: { checkins: { userId: this.userId, time: new Date() } } }
);
```

If I run this, Collection2 complains that Checkins is required. Yet, if I add { validate: false }, everything works as expected. MongoDB creates the document and pushes the user / timestamp combination to the array.

Why doesn't Collection2 accept this?

**Comment by aldeed** [comment]
If you are using the Meteor SimpleSchema package, switch to the NPM package. It should work properly with that one.
